export const transpileToC = (projectStructure, standardHeaders = []) => {
    let stdFunctions = {};
    let customIncludes = ``;

    standardHeaders.forEach(([filename, content]) => {
        customIncludes += `#include "${filename}"\n`;
        const regex = /\b([A-Za-z0-9_]+)_Call\s*\(([^)]*)\)/g;
        let match;
        while ((match = regex.exec(content)) !== null) {
            const blockType = match[1];
            const paramsStr = match[2].trim();
            const paramList = paramsStr ? paramsStr.split(',').map(s => s.trim()) : [];
            let isFB = false;

            if (paramList.length > 0 && paramList[0].includes('*')) {
                isFB = true;
                paramList.shift();
            } else if (paramList.length > 0 && paramList[0] === 'void') {
                paramList.shift();
            }

            const inputs = paramList.map(p => {
                const parts = p.split(/\s+/).filter(Boolean);
                if (parts.length === 0) return null;
                const last = parts[parts.length - 1];
                return last.replace(/[^A-Za-z0-9_]/g, '');
            }).filter(Boolean);

            stdFunctions[blockType] = {
                hasTime: paramsStr.includes('TIME'),
                inputs: inputs,
                isFB: isFB
            };
        }
    });

    const IEC_TYPE_SIZES = {
        'BOOL': 1, 'SINT': 1, 'USINT': 1,
        'INT': 2, 'UINT': 2,
        'DINT': 4, 'UDINT': 4, 'TIME': 4, 'REAL': 4
    };

    const resolveInitialValue = (val, type) => {
        if (val !== undefined && val !== null && val !== '') {
            if (type === 'BOOL') return val.toString().toLowerCase() === 'true' || val === '1';
            if (['STRING'].includes(type)) return val.toString().replace(/^"|"$/g, '');
            return Number(val) || 0;
        }
        if (type === 'BOOL') return false;
        if (['STRING'].includes(type)) return "";
        return 0;
    };

    let header = `// Autogenerated by KronEditor CTranspiler
#ifndef PLC_H
#define PLC_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
${customIncludes}

extern volatile uint64_t us_tick;

`;

    let source = `// Autogenerated by KronEditor CTranspiler\n#include "plc.h"\n\n#if defined(__linux__) || defined(__APPLE__)\n#include <time.h>\n#include <unistd.h>\n#elif defined(_WIN32)\nvoid Sleep(unsigned long ms); /* kernel32.dll, no windows.h needed */\n#endif\n\n`;

    let variableTable = {
        dataTypes: {},
        globalVars: {},
        programs: {},
        // Flat debug map: liveKey → {type, c_symbol, defaultValue}
        // Written so the simulator/developer can verify symbol tracking
        debugDefaults: {}
    };

    // 1. Data Types (Header only)
    if (projectStructure.dataTypes && projectStructure.dataTypes.length > 0) {
        header += `// --- DATA TYPES ---\n`;
        projectStructure.dataTypes.forEach(dt => {
            header += transpileDataType(dt);
            // Record structured mapping
            variableTable.dataTypes[dt.name] = {
                type: dt.type,
                content: dt.content
            };
        });
    }

    // 2. Global Variables
    const config = projectStructure.resources?.find(r => r.id === 'res_config');

    // Build lookup: typeName → data type definition (for array/struct/enum expansion)
    const dataTypeDefs = (projectStructure.dataTypes || []).reduce((acc, dt) => {
        acc[dt.name] = dt; return acc;
    }, {});

    if (config && config.content.globalVars && config.content.globalVars.length > 0) {
        header += `// --- GLOBAL VARIABLES ---\n`;
        config.content.globalVars.forEach(v => {
            const isUserType = !!dataTypeDefs[v.type];
            let initVal = (!isUserType && v.initialValue) ? ` = ${v.initialValue}` : '';
            if (v.type === 'STRING' && v.initialValue) initVal = ` = "${v.initialValue}"`;
            header += `${mapType(v.type)} ${v.name}${initVal};\n`;
            const gInitVal = resolveInitialValue(v.initialValue, v.type);
            variableTable.globalVars[v.name] = { type: v.type, initialValue: gInitVal };
            // Debug: top-level entry
            variableTable.debugDefaults[`prog__${v.name}`] = {
                type: v.type, c_symbol: v.name, defaultValue: gInitVal
            };
            // Debug: expand array elements and struct members for monitoring
            const dtDef = dataTypeDefs[v.type];
            if (dtDef?.type === 'Array') {
                const baseType = dtDef.content.baseType;
                const elemSize = IEC_TYPE_SIZES[baseType.toUpperCase()] || 0;
                dtDef.content.dimensions.forEach(dim => {
                    for (let i = parseInt(dim.min); i <= parseInt(dim.max); i++) {
                        variableTable.debugDefaults[`prog__${v.name}[${i}]`] = {
                            type: baseType, c_symbol: `${v.name}[${i}]`,
                            base_symbol: v.name, byte_offset: i * elemSize,
                            defaultValue: 0
                        };
                    }
                });
            } else if (dtDef?.type === 'Structure') {
                let memberOffset = 0;
                (dtDef.content.members || []).forEach(member => {
                    variableTable.debugDefaults[`prog__${v.name}.${member.name}`] = {
                        type: member.type, c_symbol: `${v.name}.${member.name}`,
                        base_symbol: v.name, byte_offset: memberOffset,
                        defaultValue: 0
                    };
                    memberOffset += IEC_TYPE_SIZES[member.type.toUpperCase()] || 0;
                });
            }
        });
        header += `\n`;
    }

    // 3. Function Blocks (State Structures)
    if (projectStructure.functionBlocks && projectStructure.functionBlocks.length > 0) {
        header += `// --- FUNCTION BLOCK STATES ---\n`;
        projectStructure.functionBlocks.forEach(fb => {
            header += `typedef struct {\n`;
            fb.content.variables.forEach(v => {
                header += `    ${mapType(v.type)} ${v.name};\n`;
            });
            header += `} ${fb.name};\n\n`;
        });
    }

    // 4. Function and Program Signatures
    header += `// --- SIGNATURES ---\n`;

    if (projectStructure.functions) {
        projectStructure.functions.forEach(fn => {
            const retType = mapType(fn.returnType || 'VOID');
            let fnName = (fn.name || '').trim().replace(/\s+/g, '_');
            header += `static inline ${retType} ${fnName}();\n`;
        });
    }

    if (projectStructure.functionBlocks) {
        projectStructure.functionBlocks.forEach(fb => {
            let fbName = (fb.name || '').trim().replace(/\s+/g, '_');
            header += `static inline void ${fbName}_Execute(${fbName} *instance);\n`;
        });
    }

    if (projectStructure.programs) {
        projectStructure.programs.forEach(prog => {
            let progName = (prog.name || '').trim().replace(/\s+/g, '_');
            header += `static inline void ${progName}();\n`;
        });
    }

    // Collect global variable names (used by LD transpiler to skip prog_ prefix)
    const globalVarNames = (config?.content?.globalVars || [])
        .map(v => (v.name || '').trim().replace(/\s+/g, '_'));

    header += `\n// --- IMPLEMENTATIONS ---\n`;

    if (projectStructure.functions) {
        header += `// --- FUNCTIONS ---\n`;
        projectStructure.functions.forEach(fn => {
            header += transpilePOUSource(fn, 'function', stdFunctions, fn.name, globalVarNames);
        });
    }

    if (projectStructure.functionBlocks) {
        header += `// --- FUNCTION BLOCKS ---\n`;
        projectStructure.functionBlocks.forEach(fb => {
            header += transpilePOUSource(fb, 'function_block', stdFunctions, fb.name, globalVarNames);
        });
    }

    if (projectStructure.programs) {
        header += `// --- PROGRAMS ---\n`;
        projectStructure.programs.forEach(prog => {
            let progName = (prog.name || '').trim().replace(/\s+/g, '_');

            variableTable.programs[progName] = { variables: {} };

            // Allocate static program instances of FBs if they exist
            prog.content.variables.forEach(v => {
                let vName = (v.name || '').trim().replace(/\s+/g, '_');
                if (isFBType(v.type, projectStructure) || stdFunctions[v.type]) {
                    header += `${v.type} prog_${progName}_inst_${vName};\n`;
                } else {
                    // Global internal variables for simple programs
                    header += `${mapType(v.type)} prog_${progName}_${vName};\n`;
                }

                const isFB = isFBType(v.type, projectStructure) || stdFunctions[v.type];
                const cSym = isFB ? `prog_${progName}_inst_${vName}` : `prog_${progName}_${vName}`;
                const initVal = resolveInitialValue(v.initialValue, v.type);
                variableTable.programs[progName].variables[vName] = {
                    type: v.type, c_symbol: cSym, initialValue: initVal
                };
                // Debug: top-level entry
                variableTable.debugDefaults[`prog_${progName}_${vName}`] = {
                    type: v.type, c_symbol: cSym, defaultValue: initVal
                };
                // Debug: expand array elements and struct members
                if (!isFB) {
                    const dtDef = dataTypeDefs[v.type];
                    if (dtDef?.type === 'Array') {
                        const baseType = dtDef.content.baseType;
                        const elemSize = IEC_TYPE_SIZES[baseType.toUpperCase()] || 0;
                        dtDef.content.dimensions.forEach(dim => {
                            for (let i = parseInt(dim.min); i <= parseInt(dim.max); i++) {
                                variableTable.debugDefaults[`prog_${progName}_${vName}[${i}]`] = {
                                    type: baseType, c_symbol: `${cSym}[${i}]`,
                                    base_symbol: cSym, byte_offset: i * elemSize,
                                    defaultValue: 0
                                };
                            }
                        });
                    } else if (dtDef?.type === 'Structure') {
                        let memberOffset = 0;
                        (dtDef.content.members || []).forEach(member => {
                            variableTable.debugDefaults[`prog_${progName}_${vName}.${member.name}`] = {
                                type: member.type, c_symbol: `${cSym}.${member.name}`,
                                base_symbol: cSym, byte_offset: memberOffset,
                                defaultValue: 0
                            };
                            memberOffset += IEC_TYPE_SIZES[member.type.toUpperCase()] || 0;
                        });
                    }
                }
            });
            // Collect shadow vars BEFORE transpiling so they can be declared before the function body
            const shadowVars = prog.type === 'LD'
                ? collectShadowVars(prog.content?.rungs, progName)
                : [];
            // Declare shadow tracking globals in header
            shadowVars.forEach(sv => {
                header += `${mapType(sv.type)} ${sv.symbol};\n`;
                const shortKey = sv.symbol.replace(`prog_${progName}_`, '');
                variableTable.programs[progName].variables[shortKey] = {
                    type: sv.type,
                    c_symbol: sv.symbol,
                    initialValue: 0
                };
                variableTable.debugDefaults[`prog_${progName}_${shortKey}`] = {
                    type: sv.type,
                    c_symbol: sv.symbol,
                    defaultValue: 0
                };
            });

            header += transpilePOUSource(prog, 'program', stdFunctions, progName, globalVarNames);
        });
    }

    header += `\n#endif // PLC_H\n`;

    // --- 5. DETERMINISTIC SCAN LOOP ---
    source += generateMainLoop(projectStructure, config);

    return { header, source, variableTable };
};

const isFBType = (type, structure) => {
    return structure.functionBlocks?.some(fb => fb.name === type);
};

const mapIECtoTimeUs = (iecTimeStr) => {
    if (!iecTimeStr) return 10000;
    const str = iecTimeStr.toUpperCase().replace('T#', '').replace('TIME#', '');
    if (str.endsWith('MS')) return parseInt(str.replace('MS', '')) * 1000;
    if (str.endsWith('US')) return parseInt(str.replace('US', ''));
    if (str.endsWith('S')) return parseInt(str.replace('S', '')) * 1000000;
    return 10000; // Default 10000us (10ms)
};



const generateMainLoop = (projectStructure, config) => {
    let mainSrc = `\n// --- DETERMINISTIC SCAN LOOP ---\n`;

    mainSrc += `\n// Global Tick Variable\n`;
    mainSrc += `#if defined(__linux__) || defined(__APPLE__) || defined(_WIN32)\n`;
    mainSrc += `// Defined here for simulation\n`;
    mainSrc += `extern volatile uint64_t us_tick;\n`;
    mainSrc += `volatile uint64_t us_tick = 0;\n`;
    mainSrc += `volatile int plc_stop = 0;\n`;
    mainSrc += `#else\n`;
    mainSrc += `// For Cortex-M4 and bare-metal targets, us_tick MUST be defined\n`;
    mainSrc += `// and incremented in your hardware timer interrupt.\n`;
    mainSrc += `// Example: volatile uint64_t us_tick = 0; void Timer_Handler(void) { us_tick += 10; }\n`;
    mainSrc += `#endif\n\n`;
    // Provide a Cortex-M4 compatible fallback main loop
    mainSrc += `#if defined(__linux__) || defined(__APPLE__) || defined(_WIN32)\n`;
    mainSrc += `int main() {\n`;

    // 1. Tick trackers (platform-specific sleep setup)
    mainSrc += `#if defined(__linux__) || defined(__APPLE__)\n`;
    mainSrc += `    struct timespec req, rem;\n`;
    mainSrc += `    req.tv_sec = 0;\n`;
    mainSrc += `    req.tv_nsec = 1000000; // 1ms\n`;
    mainSrc += `#endif\n\n`;

    // 2. Discover Task mappings and Instances
    let programTasks = [];

    if (config && config.content.instances) {
        config.content.instances.forEach(inst => {
            const task = config.content.tasks?.find(t => t.name === inst.task);
            let pName = (inst.program || '').trim().replace(/\s+/g, '_');
            if (task) {
                programTasks.push({
                    name: pName,
                    intervalUs: mapIECtoTimeUs(task.interval)
                });
            } else {
                programTasks.push({ name: pName, intervalUs: 10000 }); // Default 10ms
            }
        });
    } else if (projectStructure.programs) {
        projectStructure.programs.forEach(p => {
            let pName = (p.name || '').trim().replace(/\s+/g, '_');
            programTasks.push({ name: pName, intervalUs: 10000 });
        });
    }

    // Ensure execution order matches definition order in projectStructure.programs
    if (projectStructure.programs && projectStructure.programs.length > 0) {
        const programOrder = projectStructure.programs.map(p => (p.name || '').trim().replace(/\s+/g, '_'));
        programTasks.sort((a, b) => {
            const ai = programOrder.indexOf(a.name);
            const bi = programOrder.indexOf(b.name);
            return (ai < 0 ? Infinity : ai) - (bi < 0 ? Infinity : bi);
        });
    }

    mainSrc += `    while(!plc_stop) {\n`;

    // 3. Scan logic
    programTasks.forEach(pt => {
        mainSrc += `        if (us_tick % ${pt.intervalUs} == 0) {\n`;
        mainSrc += `            ${pt.name}();\n`;
        mainSrc += `        }\n`;
    });

    // 4. Advance time (platform-specific 1ms sleep)
    mainSrc += `#if defined(__linux__) || defined(__APPLE__)\n`;
    mainSrc += `        nanosleep(&req, &rem);\n`;
    mainSrc += `#elif defined(_WIN32)\n`;
    mainSrc += `        Sleep(1);\n`;
    mainSrc += `#endif\n`;
    mainSrc += `        us_tick += 1000;\n`; // Advance 1000us (1ms)
    mainSrc += `    }\n`;
    mainSrc += `    return 0;\n}\n`;

    mainSrc += `#else\n\n`;
    mainSrc += `// Bare-metal / Cortex-M4 execution engine\n`;
    mainSrc += `// You must provide a timer to increment us_tick\n`;
    mainSrc += `void PLC_Run() {\n`;
    programTasks.forEach(pt => {
        mainSrc += `    if (us_tick % ${pt.intervalUs} == 0) {\n`;
        mainSrc += `        ${pt.name}();\n`;
        mainSrc += `    }\n`;
    });
    mainSrc += `}\n\n`;
    mainSrc += `#endif\n`;

    return mainSrc;
};

const transpilePOUSource = (pou, category, stdFunctions = {}, parentName = '', globalVarNames = []) => {
    let src = ``;
    let safeName = (pou.name || '').trim().replace(/\s+/g, '_');
    let sig = `static inline void ${safeName}()`;

    if (category === 'function') {
        const retType = mapType(pou.returnType || 'VOID');
        sig = `static inline ${retType} ${safeName}()`;
    } else if (category === 'function_block') {
        sig = `static inline void ${safeName}_Execute(${safeName} *instance)`;
    }

    src += `${sig} {\n`;

    if (pou.type === 'ST') {
        // Build variable name map: IEC identifier → C symbol
        const varMap = {};
        (pou.content.variables || []).forEach(v => {
            const vName = (v.name || '').trim().replace(/\s+/g, '_');
            if (!vName) return;
            if (globalVarNames.includes(vName)) {
                varMap[vName] = vName; // global vars: no prefix
            } else if (category === 'program') {
                const isFB = stdFunctions[v.type] !== undefined;
                varMap[vName] = isFB
                    ? `prog_${parentName}_inst_${vName}`
                    : `prog_${parentName}_${vName}`;
            } else if (category === 'function_block') {
                varMap[vName] = `instance->${vName}`;
            } else {
                varMap[vName] = vName;
            }
        });
        src += transpileSTLogics(pou.content.code, stdFunctions, parentName, category, varMap);
    } else if (pou.type === 'LD') {
        src += transpileLDLogics(pou.content.rungs, stdFunctions, safeName, category, globalVarNames);
    }

    src += `}\n\n`;
    return src;
};

// --- LD Block Type Definitions (mirrors blockConfig in RungContainer) ---
// Trigger (first/power-flow) input pin for each standard FB type
const FB_TRIGGER_PIN = {
    // Timers
    'TON': 'IN', 'TOF': 'IN', 'TP': 'IN', 'TONR': 'IN',
    // Counters
    'CTU': 'CU', 'CTD': 'CD', 'CTUD': 'CU',
    // Edge detectors
    'R_TRIG': 'CLK', 'F_TRIG': 'CLK',
    // Bistable
    'RS': 'S', 'SR': 'S1',
    // Comparison / Arithmetic / Math / Bitwise / Trig / Selection / Conversion — EN is the power-flow input
    'GT': 'EN', 'GE': 'EN', 'EQ': 'EN', 'NE': 'EN', 'LE': 'EN', 'LT': 'EN',
    'ADD': 'EN', 'SUB': 'EN', 'MUL': 'EN', 'DIV': 'EN', 'MOD': 'EN', 'MOVE': 'EN',
    'ABS': 'EN', 'SQRT': 'EN', 'EXPT': 'EN', 'MAX': 'EN', 'MIN': 'EN', 'LIMIT': 'EN',
    'BAND': 'EN', 'BOR': 'EN', 'BXOR': 'EN', 'BNOT': 'EN',
    'SHL': 'EN', 'SHR': 'EN', 'ROL': 'EN', 'ROR': 'EN',
    'SIN': 'EN', 'COS': 'EN', 'TAN': 'EN', 'ASIN': 'EN', 'ACOS': 'EN', 'ATAN': 'EN',
    'SEL': 'EN', 'MUX': 'EN',
    // Conversion (all 72 — EN is trigger)
    'BYTE_TO_BOOL': 'EN', 'WORD_TO_BOOL': 'EN', 'DWORD_TO_BOOL': 'EN', 'INT_TO_BOOL': 'EN',
    'UINT_TO_BOOL': 'EN', 'DINT_TO_BOOL': 'EN', 'UDINT_TO_BOOL': 'EN', 'REAL_TO_BOOL': 'EN',
    'BOOL_TO_BYTE': 'EN', 'WORD_TO_BYTE': 'EN', 'DWORD_TO_BYTE': 'EN', 'INT_TO_BYTE': 'EN',
    'UINT_TO_BYTE': 'EN', 'DINT_TO_BYTE': 'EN', 'UDINT_TO_BYTE': 'EN', 'REAL_TO_BYTE': 'EN',
    'BOOL_TO_WORD': 'EN', 'BYTE_TO_WORD': 'EN', 'DWORD_TO_WORD': 'EN', 'INT_TO_WORD': 'EN',
    'UINT_TO_WORD': 'EN', 'DINT_TO_WORD': 'EN', 'UDINT_TO_WORD': 'EN', 'REAL_TO_WORD': 'EN',
    'BOOL_TO_DWORD': 'EN', 'BYTE_TO_DWORD': 'EN', 'WORD_TO_DWORD': 'EN', 'INT_TO_DWORD': 'EN',
    'UINT_TO_DWORD': 'EN', 'DINT_TO_DWORD': 'EN', 'UDINT_TO_DWORD': 'EN', 'REAL_TO_DWORD': 'EN',
    'BOOL_TO_INT': 'EN', 'BYTE_TO_INT': 'EN', 'WORD_TO_INT': 'EN', 'DWORD_TO_INT': 'EN',
    'UINT_TO_INT': 'EN', 'DINT_TO_INT': 'EN', 'UDINT_TO_INT': 'EN', 'REAL_TO_INT': 'EN',
    'BOOL_TO_UINT': 'EN', 'BYTE_TO_UINT': 'EN', 'WORD_TO_UINT': 'EN', 'DWORD_TO_UINT': 'EN',
    'INT_TO_UINT': 'EN', 'DINT_TO_UINT': 'EN', 'UDINT_TO_UINT': 'EN', 'REAL_TO_UINT': 'EN',
    'BOOL_TO_DINT': 'EN', 'BYTE_TO_DINT': 'EN', 'WORD_TO_DINT': 'EN', 'DWORD_TO_DINT': 'EN',
    'INT_TO_DINT': 'EN', 'UINT_TO_DINT': 'EN', 'UDINT_TO_DINT': 'EN', 'REAL_TO_DINT': 'EN',
    'BOOL_TO_UDINT': 'EN', 'BYTE_TO_UDINT': 'EN', 'WORD_TO_UDINT': 'EN', 'DWORD_TO_UDINT': 'EN',
    'INT_TO_UDINT': 'EN', 'UINT_TO_UDINT': 'EN', 'DINT_TO_UDINT': 'EN', 'REAL_TO_UDINT': 'EN',
    'BOOL_TO_REAL': 'EN', 'BYTE_TO_REAL': 'EN', 'WORD_TO_REAL': 'EN', 'DWORD_TO_REAL': 'EN',
    'INT_TO_REAL': 'EN', 'UINT_TO_REAL': 'EN', 'DINT_TO_REAL': 'EN', 'UDINT_TO_REAL': 'EN',
    'NORM_X': 'EN', 'SCALE_X': 'EN'
};

// Primary boolean output pin for downstream power flow
const FB_Q_OUTPUT = {
    // Timers
    'TON': 'Q', 'TOF': 'Q', 'TP': 'Q', 'TONR': 'Q',
    // Counters
    'CTU': 'Q', 'CTD': 'Q', 'CTUD': 'QU',
    // Edge detectors
    'R_TRIG': 'Q', 'F_TRIG': 'Q',
    // Bistable
    'RS': 'Q1', 'SR': 'Q1',
    // Comparison: ENO = EN && (result) — acts as conditional power flow
    'GT': 'ENO', 'GE': 'ENO', 'EQ': 'ENO', 'NE': 'ENO', 'LE': 'ENO', 'LT': 'ENO',
    // Arithmetic / Math / Bitwise / Trig / Selection / Conversion: ENO = EN — passes power through
    'ADD': 'ENO', 'SUB': 'ENO', 'MUL': 'ENO', 'DIV': 'ENO', 'MOD': 'ENO', 'MOVE': 'ENO',
    'ABS': 'ENO', 'SQRT': 'ENO', 'EXPT': 'ENO', 'MAX': 'ENO', 'MIN': 'ENO', 'LIMIT': 'ENO',
    'BAND': 'ENO', 'BOR': 'ENO', 'BXOR': 'ENO', 'BNOT': 'ENO',
    'SHL': 'ENO', 'SHR': 'ENO', 'ROL': 'ENO', 'ROR': 'ENO',
    'SIN': 'ENO', 'COS': 'ENO', 'TAN': 'ENO', 'ASIN': 'ENO', 'ACOS': 'ENO', 'ATAN': 'ENO',
    'SEL': 'ENO', 'MUX': 'ENO',
    // Conversion (all 72 — ENO passes power through)
    'BYTE_TO_BOOL': 'ENO', 'WORD_TO_BOOL': 'ENO', 'DWORD_TO_BOOL': 'ENO', 'INT_TO_BOOL': 'ENO',
    'UINT_TO_BOOL': 'ENO', 'DINT_TO_BOOL': 'ENO', 'UDINT_TO_BOOL': 'ENO', 'REAL_TO_BOOL': 'ENO',
    'BOOL_TO_BYTE': 'ENO', 'WORD_TO_BYTE': 'ENO', 'DWORD_TO_BYTE': 'ENO', 'INT_TO_BYTE': 'ENO',
    'UINT_TO_BYTE': 'ENO', 'DINT_TO_BYTE': 'ENO', 'UDINT_TO_BYTE': 'ENO', 'REAL_TO_BYTE': 'ENO',
    'BOOL_TO_WORD': 'ENO', 'BYTE_TO_WORD': 'ENO', 'DWORD_TO_WORD': 'ENO', 'INT_TO_WORD': 'ENO',
    'UINT_TO_WORD': 'ENO', 'DINT_TO_WORD': 'ENO', 'UDINT_TO_WORD': 'ENO', 'REAL_TO_WORD': 'ENO',
    'BOOL_TO_DWORD': 'ENO', 'BYTE_TO_DWORD': 'ENO', 'WORD_TO_DWORD': 'ENO', 'INT_TO_DWORD': 'ENO',
    'UINT_TO_DWORD': 'ENO', 'DINT_TO_DWORD': 'ENO', 'UDINT_TO_DWORD': 'ENO', 'REAL_TO_DWORD': 'ENO',
    'BOOL_TO_INT': 'ENO', 'BYTE_TO_INT': 'ENO', 'WORD_TO_INT': 'ENO', 'DWORD_TO_INT': 'ENO',
    'UINT_TO_INT': 'ENO', 'DINT_TO_INT': 'ENO', 'UDINT_TO_INT': 'ENO', 'REAL_TO_INT': 'ENO',
    'BOOL_TO_UINT': 'ENO', 'BYTE_TO_UINT': 'ENO', 'WORD_TO_UINT': 'ENO', 'DWORD_TO_UINT': 'ENO',
    'INT_TO_UINT': 'ENO', 'DINT_TO_UINT': 'ENO', 'UDINT_TO_UINT': 'ENO', 'REAL_TO_UINT': 'ENO',
    'BOOL_TO_DINT': 'ENO', 'BYTE_TO_DINT': 'ENO', 'WORD_TO_DINT': 'ENO', 'DWORD_TO_DINT': 'ENO',
    'INT_TO_DINT': 'ENO', 'UINT_TO_DINT': 'ENO', 'UDINT_TO_DINT': 'ENO', 'REAL_TO_DINT': 'ENO',
    'BOOL_TO_UDINT': 'ENO', 'BYTE_TO_UDINT': 'ENO', 'WORD_TO_UDINT': 'ENO', 'DWORD_TO_UDINT': 'ENO',
    'INT_TO_UDINT': 'ENO', 'UINT_TO_UDINT': 'ENO', 'DINT_TO_UDINT': 'ENO', 'REAL_TO_UDINT': 'ENO',
    'BOOL_TO_REAL': 'ENO', 'BYTE_TO_REAL': 'ENO', 'WORD_TO_REAL': 'ENO', 'DWORD_TO_REAL': 'ENO',
    'INT_TO_REAL': 'ENO', 'UINT_TO_REAL': 'ENO', 'DINT_TO_REAL': 'ENO', 'UDINT_TO_REAL': 'ENO',
    'NORM_X': 'ENO', 'SCALE_X': 'ENO'
};

// Returns the IEC type of an output pin for a given block type
const getOutputPinType = (blockType, pinName) => {
    if (['Q', 'Q1', 'QU', 'QD', 'ENO'].includes(pinName)) return 'BOOL';
    if (pinName === 'ET') return 'TIME';
    if (pinName === 'CV') return 'INT';
    if (pinName === 'OUT') {
        const m = blockType.match(/_TO_([A-Z]+)$/);
        if (m) return m[1];
        if (['ADD', 'SUB', 'MUL', 'DIV', 'MOD', 'MOVE', 'SEL', 'MUX'].includes(blockType)) return 'DINT';
        if (['ABS', 'SQRT', 'EXPT', 'MAX', 'MIN', 'LIMIT', 'SIN', 'COS', 'TAN', 'ASIN', 'ACOS', 'ATAN', 'NORM_X', 'SCALE_X'].includes(blockType)) return 'REAL';
        if (['BAND', 'BOR', 'BXOR', 'BNOT', 'SHL', 'SHR', 'ROL', 'ROR'].includes(blockType)) return 'DWORD';
    }
    return 'BOOL';
};

// Pre-scan rungs and collect shadow variables for unassigned FB output pins.
// These become global C variables so the simulator can track them.
const collectShadowVars = (rungs, progName) => {
    const seen = new Set();
    const vars = [];
    (rungs || []).forEach(rung => {
        (rung.blocks || []).forEach(b => {
            const type = b.type || '';
            const data = b.data || {};
            if (type === 'Contact' || type === 'Coil') return;
            const instName = (data.instanceName || type).trim().replace(/\s+/g, '_');
            const outPins = [
                ...(FB_OUTPUTS[type] || []),
                ...(data.customData?.content?.variables || [])
                    .filter(v => v.class === 'Output').map(v => v.name)
            ];
            outPins.forEach(pinName => {
                const assigned = ((data.values?.[pinName] || '') + '').replace(/[🌍🏠⊞⊡⊟]/g, '').trim();
                const isAssigned = assigned && /^[A-Za-z_][A-Za-z0-9_]*(\[[^\]]*\]|\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(assigned);
                if (!isAssigned) {
                    const sym = `prog_${progName}_out_${instName}_${pinName}`;
                    if (!seen.has(sym)) {
                        seen.add(sym);
                        vars.push({ symbol: sym, type: getOutputPinType(type, pinName) });
                    }
                }
            });
        });
    });
    return vars;
};

// Output pin names for each standard FB type (used to separate read-back assignments)
const FB_OUTPUTS = {
    'TON': ['Q', 'ET'], 'TOF': ['Q', 'ET'], 'TP': ['Q', 'ET'], 'TONR': ['Q', 'ET'],
    'CTU': ['Q', 'CV'], 'CTD': ['Q', 'CV'], 'CTUD': ['QU', 'QD', 'CV'],
    'SR': ['Q1'], 'RS': ['Q1'],
    'R_TRIG': ['Q'], 'F_TRIG': ['Q'],
    // Comparison — ENO only
    'GT': ['ENO'], 'GE': ['ENO'], 'EQ': ['ENO'], 'NE': ['ENO'], 'LE': ['ENO'], 'LT': ['ENO'],
    // Arithmetic / Math / Bitwise / Trig / Selection — ENO + OUT
    'ADD': ['ENO', 'OUT'], 'SUB': ['ENO', 'OUT'], 'MUL': ['ENO', 'OUT'],
    'DIV': ['ENO', 'OUT'], 'MOD': ['ENO', 'OUT'], 'MOVE': ['ENO', 'OUT'],
    'ABS': ['ENO', 'OUT'], 'SQRT': ['ENO', 'OUT'], 'EXPT': ['ENO', 'OUT'],
    'MAX': ['ENO', 'OUT'], 'MIN': ['ENO', 'OUT'], 'LIMIT': ['ENO', 'OUT'],
    'BAND': ['ENO', 'OUT'], 'BOR': ['ENO', 'OUT'], 'BXOR': ['ENO', 'OUT'], 'BNOT': ['ENO', 'OUT'],
    'SHL': ['ENO', 'OUT'], 'SHR': ['ENO', 'OUT'], 'ROL': ['ENO', 'OUT'], 'ROR': ['ENO', 'OUT'],
    'SIN': ['ENO', 'OUT'], 'COS': ['ENO', 'OUT'], 'TAN': ['ENO', 'OUT'],
    'ASIN': ['ENO', 'OUT'], 'ACOS': ['ENO', 'OUT'], 'ATAN': ['ENO', 'OUT'],
    'SEL': ['ENO', 'OUT'], 'MUX': ['ENO', 'OUT'],
    'NORM_X': ['ENO', 'OUT'], 'SCALE_X': ['ENO', 'OUT'],
};
// All conversion blocks (X_TO_Y) share ['ENO', 'OUT'] — built dynamically below
Object.keys(FB_OUTPUTS).length; // dummy to close initializer
['BOOL', 'BYTE', 'WORD', 'DWORD', 'INT', 'UINT', 'DINT', 'UDINT', 'REAL'].forEach(src => {
    ['BOOL', 'BYTE', 'WORD', 'DWORD', 'INT', 'UINT', 'DINT', 'UDINT', 'REAL'].forEach(dst => {
        if (src !== dst) FB_OUTPUTS[`${src}_TO_${dst}`] = ['ENO', 'OUT'];
    });
});

// Ordered input pin names for each standard FB type (index matches in_0, in_1, ...)
const FB_INPUTS = {
    'TON': ['IN', 'PT'],
    'TOF': ['IN', 'PT'],
    'TP': ['IN', 'PT'],
    'TONR': ['IN', 'PT', 'RESET'],
    'CTU': ['CU', 'R', 'PV'],
    'CTD': ['CD', 'LD', 'PV'],
    'CTUD': ['CU', 'CD', 'R', 'LD', 'PV'],
    'R_TRIG': ['CLK'],
    'F_TRIG': ['CLK'],
    'RS': ['S', 'R1'],
    'SR': ['S1', 'R'],
    // Comparison
    'GT': ['EN', 'IN1', 'IN2'], 'GE': ['EN', 'IN1', 'IN2'], 'EQ': ['EN', 'IN1', 'IN2'],
    'NE': ['EN', 'IN1', 'IN2'], 'LE': ['EN', 'IN1', 'IN2'], 'LT': ['EN', 'IN1', 'IN2'],
    // Arithmetic
    'ADD': ['EN', 'IN1', 'IN2'], 'SUB': ['EN', 'IN1', 'IN2'],
    'MUL': ['EN', 'IN1', 'IN2'], 'DIV': ['EN', 'IN1', 'IN2'],
    'MOD': ['EN', 'IN1', 'IN2'], 'MOVE': ['EN', 'IN'],
    // Math
    'ABS': ['EN', 'IN'], 'SQRT': ['EN', 'IN'],
    'EXPT': ['EN', 'IN', 'EXP'],
    'MAX': ['EN', 'IN1', 'IN2'], 'MIN': ['EN', 'IN1', 'IN2'],
    'LIMIT': ['EN', 'IN', 'MN', 'MX'],
    // Bitwise
    'BAND': ['EN', 'IN1', 'IN2'], 'BOR': ['EN', 'IN1', 'IN2'],
    'BXOR': ['EN', 'IN1', 'IN2'], 'BNOT': ['EN', 'IN'],
    'SHL': ['EN', 'IN', 'N'], 'SHR': ['EN', 'IN', 'N'],
    'ROL': ['EN', 'IN', 'N'], 'ROR': ['EN', 'IN', 'N'],
    // Trig
    'SIN': ['EN', 'IN'], 'COS': ['EN', 'IN'], 'TAN': ['EN', 'IN'],
    'ASIN': ['EN', 'IN'], 'ACOS': ['EN', 'IN'], 'ATAN': ['EN', 'IN'],
    // Selection
    'SEL': ['EN', 'G', 'IN0', 'IN1'],
    'MUX': ['EN', 'K', 'IN0', 'IN1'],
    // Conversion (all 72 — ['EN', 'IN'] pattern)
    'BYTE_TO_BOOL': ['EN', 'IN'], 'WORD_TO_BOOL': ['EN', 'IN'], 'DWORD_TO_BOOL': ['EN', 'IN'],
    'INT_TO_BOOL': ['EN', 'IN'], 'UINT_TO_BOOL': ['EN', 'IN'], 'DINT_TO_BOOL': ['EN', 'IN'],
    'UDINT_TO_BOOL': ['EN', 'IN'], 'REAL_TO_BOOL': ['EN', 'IN'],
    'BOOL_TO_BYTE': ['EN', 'IN'], 'WORD_TO_BYTE': ['EN', 'IN'], 'DWORD_TO_BYTE': ['EN', 'IN'],
    'INT_TO_BYTE': ['EN', 'IN'], 'UINT_TO_BYTE': ['EN', 'IN'], 'DINT_TO_BYTE': ['EN', 'IN'],
    'UDINT_TO_BYTE': ['EN', 'IN'], 'REAL_TO_BYTE': ['EN', 'IN'],
    'BOOL_TO_WORD': ['EN', 'IN'], 'BYTE_TO_WORD': ['EN', 'IN'], 'DWORD_TO_WORD': ['EN', 'IN'],
    'INT_TO_WORD': ['EN', 'IN'], 'UINT_TO_WORD': ['EN', 'IN'], 'DINT_TO_WORD': ['EN', 'IN'],
    'UDINT_TO_WORD': ['EN', 'IN'], 'REAL_TO_WORD': ['EN', 'IN'],
    'BOOL_TO_DWORD': ['EN', 'IN'], 'BYTE_TO_DWORD': ['EN', 'IN'], 'WORD_TO_DWORD': ['EN', 'IN'],
    'INT_TO_DWORD': ['EN', 'IN'], 'UINT_TO_DWORD': ['EN', 'IN'], 'DINT_TO_DWORD': ['EN', 'IN'],
    'UDINT_TO_DWORD': ['EN', 'IN'], 'REAL_TO_DWORD': ['EN', 'IN'],
    'BOOL_TO_INT': ['EN', 'IN'], 'BYTE_TO_INT': ['EN', 'IN'], 'WORD_TO_INT': ['EN', 'IN'],
    'DWORD_TO_INT': ['EN', 'IN'], 'UINT_TO_INT': ['EN', 'IN'], 'DINT_TO_INT': ['EN', 'IN'],
    'UDINT_TO_INT': ['EN', 'IN'], 'REAL_TO_INT': ['EN', 'IN'],
    'BOOL_TO_UINT': ['EN', 'IN'], 'BYTE_TO_UINT': ['EN', 'IN'], 'WORD_TO_UINT': ['EN', 'IN'],
    'DWORD_TO_UINT': ['EN', 'IN'], 'INT_TO_UINT': ['EN', 'IN'], 'DINT_TO_UINT': ['EN', 'IN'],
    'UDINT_TO_UINT': ['EN', 'IN'], 'REAL_TO_UINT': ['EN', 'IN'],
    'BOOL_TO_DINT': ['EN', 'IN'], 'BYTE_TO_DINT': ['EN', 'IN'], 'WORD_TO_DINT': ['EN', 'IN'],
    'DWORD_TO_DINT': ['EN', 'IN'], 'INT_TO_DINT': ['EN', 'IN'], 'UINT_TO_DINT': ['EN', 'IN'],
    'UDINT_TO_DINT': ['EN', 'IN'], 'REAL_TO_DINT': ['EN', 'IN'],
    'BOOL_TO_UDINT': ['EN', 'IN'], 'BYTE_TO_UDINT': ['EN', 'IN'], 'WORD_TO_UDINT': ['EN', 'IN'],
    'DWORD_TO_UDINT': ['EN', 'IN'], 'INT_TO_UDINT': ['EN', 'IN'], 'UINT_TO_UDINT': ['EN', 'IN'],
    'DINT_TO_UDINT': ['EN', 'IN'], 'REAL_TO_UDINT': ['EN', 'IN'],
    'BOOL_TO_REAL': ['EN', 'IN'], 'BYTE_TO_REAL': ['EN', 'IN'], 'WORD_TO_REAL': ['EN', 'IN'],
    'DWORD_TO_REAL': ['EN', 'IN'], 'INT_TO_REAL': ['EN', 'IN'], 'UINT_TO_REAL': ['EN', 'IN'],
    'DINT_TO_REAL': ['EN', 'IN'], 'UDINT_TO_REAL': ['EN', 'IN'],
    // Scaling
    'NORM_X': ['EN', 'MIN', 'MAX', 'VALUE'],
    'SCALE_X': ['EN', 'MIN', 'MAX', 'VALUE']
};

const transpileSTLogics = (code, stdFunctions = {}, parentName = '', category = 'program', varMap = {}) => {
    if (!code) return `    // ST Implementation Empty\n`;

    // Split on actual newlines or escaped \n sequences (both may appear depending on storage)
    const lines = code.split(/\r?\n|\\n/);
    let out = '';
    let indentLevel = 1; // 1 = inside function body (4 spaces)

    const indent = () => '    '.repeat(indentLevel);

    // Substitute known variable names with their C equivalents
    const resolveVarsInExpr = (expr) => {
        const sortedNames = Object.keys(varMap).sort((a, b) => b.length - a.length);
        let result = expr;
        sortedNames.forEach(name => {
            result = result.replace(new RegExp(`\\b${name}\\b`, 'g'), varMap[name]);
        });
        return result;
    };

    const transformExpr = (expr) => {
        let result = expr
            .replace(/\b[A-Za-z_][A-Za-z0-9_]*#([A-Za-z_][A-Za-z0-9_]*)\b/g, '$1') // TypeName#EnumValue → EnumValue
            .replace(/:=/g, '=')
            .replace(/\bAND\b/g, '&&')
            .replace(/\bOR\b/g, '||')
            .replace(/\bNOT\b/g, '!')
            .replace(/\bMOD\b/g, '%')
            .replace(/\bXOR\b/g, '^')
            .replace(/\bTRUE\b/gi, 'true')
            .replace(/\bFALSE\b/gi, 'false');
        return resolveVarsInExpr(result);
    };

    lines.forEach(line => {
        const trimmed = line.trim();
        if (!trimmed) return;

        // ── Block closing keywords ────────────────────────────────────────
        if (/^END_IF\s*;?$/i.test(trimmed)) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}}\n`;
            return;
        }
        if (/^END_FOR\s*;?$/i.test(trimmed)) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}}\n`;
            return;
        }
        if (/^END_WHILE\s*;?$/i.test(trimmed)) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}}\n`;
            return;
        }

        // ── ELSIF / ELSE IF (check before standalone ELSE) ────────────────
        const elsifMatch = trimmed.match(/^(?:ELSIF|ELSE\s+IF)\s+(.+?)\s+THEN\s*;?\s*$/i);
        if (elsifMatch) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}} else if (${transformExpr(elsifMatch[1])}) {\n`;
            indentLevel++;
            return;
        }

        // ── ELSE ──────────────────────────────────────────────────────────
        if (/^ELSE\s*;?\s*$/i.test(trimmed)) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}} else {\n`;
            indentLevel++;
            return;
        }

        // ── IF ... THEN ───────────────────────────────────────────────────
        const ifMatch = trimmed.match(/^IF\s+(.+?)\s+THEN\s*;?\s*$/i);
        if (ifMatch) {
            out += `${indent()}if (${transformExpr(ifMatch[1])}) {\n`;
            indentLevel++;
            return;
        }

        // ── FOR ... TO ... BY ... DO (BY clause first — more specific) ────
        const forByMatch = trimmed.match(/^FOR\s+(\w+)\s*:=\s*(.+?)\s+TO\s+(.+?)\s+BY\s+(.+?)\s+DO\s*;?\s*$/i);
        if (forByMatch) {
            const [, vn, start, end, step] = forByMatch;
            const cv = varMap[vn] || vn;
            out += `${indent()}for (${cv} = ${transformExpr(start)}; ${cv} <= ${transformExpr(end)}; ${cv} += ${transformExpr(step)}) {\n`;
            indentLevel++;
            return;
        }

        // ── FOR ... TO ... DO ─────────────────────────────────────────────
        const forMatch = trimmed.match(/^FOR\s+(\w+)\s*:=\s*(.+?)\s+TO\s+(.+?)\s+DO\s*;?\s*$/i);
        if (forMatch) {
            const [, vn, start, end] = forMatch;
            const cv = varMap[vn] || vn;
            out += `${indent()}for (${cv} = ${transformExpr(start)}; ${cv} <= ${transformExpr(end)}; ${cv}++) {\n`;
            indentLevel++;
            return;
        }

        // ── WHILE ... DO ──────────────────────────────────────────────────
        const whileMatch = trimmed.match(/^WHILE\s+(.+?)\s+DO\s*;?\s*$/i);
        if (whileMatch) {
            out += `${indent()}while (${transformExpr(whileMatch[1])}) {\n`;
            indentLevel++;
            return;
        }

        // ── REPEAT (do-while start) ───────────────────────────────────────
        if (/^REPEAT\s*;?\s*$/i.test(trimmed)) {
            out += `${indent()}do {\n`;
            indentLevel++;
            return;
        }

        // ── UNTIL (do-while end) ──────────────────────────────────────────
        const untilMatch = trimmed.match(/^UNTIL\s+(.+?)\s*;?\s*$/i);
        if (untilMatch) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}} while (!(${transformExpr(untilMatch[1])}));\n`;
            return;
        }

        // ── EXIT → break ──────────────────────────────────────────────────
        if (/^EXIT\s*;?\s*$/i.test(trimmed)) {
            out += `${indent()}break;\n`;
            return;
        }

        // ── RETURN ────────────────────────────────────────────────────────
        if (/^RETURN\b/i.test(trimmed)) {
            const retVal = trimmed.replace(/^RETURN\s*/i, '').replace(/;$/, '').trim();
            out += `${indent()}return${retVal ? ` ${transformExpr(retVal)}` : ''};\n`;
            return;
        }

        // ── Regular statement (assignment, function call, etc.) ───────────
        let cl = transformExpr(trimmed);
        if (!cl.endsWith(';')) cl += ';';
        out += `${indent()}${cl}\n`;
    });

    return out || `    // ST parsing placeholder\n`;
};

const transpileLDLogics = (rungs, stdFunctions = {}, parentName = '', category = 'program', globalVarNames = []) => {
    if (!rungs || rungs.length === 0) return `    // LD Implementation Empty\n`;

    let out = '';

    // Resolve a variable/signal name to its C symbol, respecting scope.
    // Handles simple names, array elements (var[idx]), struct members (var.member).
    const resolveVar = (varName) => {
        if (!varName) return null;
        const s = varName.trim();
        // Split base name from suffix (array index or struct member access)
        const sepIdx = s.search(/[\[.]/);
        const baseName = (sepIdx >= 0 ? s.slice(0, sepIdx) : s).replace(/\s+/g, '_');
        const suffix = sepIdx >= 0 ? s.slice(sepIdx) : '';
        if (category === 'program') {
            // Global vars: no prefix; local program vars: prog_<name>_ prefix
            const resolved = globalVarNames.includes(baseName) ? baseName : `prog_${parentName}_${baseName}`;
            return resolved + suffix;
        }
        if (category === 'function_block') return `instance->${baseName}${suffix}`;
        return s;
    };

    // Resolve a value string: IEC time literal → us integer, numeric → as-is,
    // identifier (incl. arr[idx] and struct.member) → scoped C symbol
    const resolveVal = (val) => {
        if (!val && val !== 0) return null;
        // Strip any UI scope/type icons (🌍🏠⊞⊡⊟)
        const s = val.toString().replace(/[🌍🏠⊞⊡⊟]/g, '').trim();
        if (!s) return null;
        if (s.toUpperCase().startsWith('T#') || s.toUpperCase().startsWith('TIME#')) {
            return mapIECtoTimeUs(s).toString();
        }
        // Numeric literal (int, float, hex)
        if (/^-?[0-9][0-9a-fA-FxX.]*$/.test(s)) return s;
        // Boolean literals
        if (/^(true|false|TRUE|FALSE)$/.test(s)) return s.toLowerCase();
        // Variable reference: simple, arr[idx], or struct.member
        if (/^[A-Za-z_][A-Za-z0-9_]*(\[[^\]]*\]|\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(s)) {
            return resolveVar(s);
        }
        return null; // unrecognised
    };

    // Get the C call-target for an FB instance
    const getCallTarget = (instName) => {
        const i = (instName || '').trim().replace(/\s+/g, '_');
        if (category === 'program') return `prog_${parentName}_inst_${i}`;
        if (category === 'function_block') return `instance->${i}`;
        return i;
    };

    rungs.forEach((rung, rungIdx) => {
        out += `    // Rung ${rungIdx}\n`;

        if (!rung.blocks || rung.blocks.length === 0) {
            out += `    // Empty Rung\n`;
            return;
        }

        // 1. Build adjacency graph (block-to-block only; terminal connections excluded)
        const adjacency = {};
        const incoming = {};
        const nodeMap = {};

        rung.blocks.forEach(b => {
            nodeMap[b.id] = b;
            adjacency[b.id] = [];
            incoming[b.id] = 0;
        });

        // Track unique source→target pairs so duplicate connections don't skew in-degree
        const addedEdges = new Set();
        (rung.connections || []).forEach(c => {
            const edgeKey = `${c.source}->${c.target}`;
            if (
                adjacency[c.source] !== undefined &&
                incoming[c.target] !== undefined &&
                !addedEdges.has(edgeKey)
            ) {
                addedEdges.add(edgeKey);
                adjacency[c.source].push(c.target);
                incoming[c.target]++;
            }
        });

        // 2. Topological sort (Kahn's algorithm)
        const queue = [];
        const sorted = [];
        Object.keys(incoming).forEach(id => {
            if (incoming[id] === 0) queue.push(id);
        });
        while (queue.length > 0) {
            const curr = queue.shift();
            sorted.push(curr);
            adjacency[curr].forEach(child => {
                incoming[child]--;
                if (incoming[child] === 0) queue.push(child);
            });
        }
        // Append any blocks not reached (disconnected sub-graphs / cycles)
        rung.blocks.forEach(b => {
            if (!sorted.includes(b.id)) sorted.push(b.id);
        });

        // Index map: blockId → position in sorted array
        const sortedIndex = {};
        sorted.forEach((id, idx) => { sortedIndex[id] = idx; });

        // Build power-flow (inExpr) for a block:
        //   Contact / Coil use handle id "in"
        //   FB first input uses "in_0"
        //   Multiple parallel paths converging are OR'd
        const getInExpr = (blockId, blockType) => {
            const isSimple = blockType === 'Contact' || blockType === 'Coil';
            const conds = [];
            (rung.connections || []).forEach(c => {
                if (c.target !== blockId) return;
                // Accept only the power-flow target handle
                const tp = c.targetPin;
                const isFlowPin = isSimple
                    ? (tp === 'in' || !tp)
                    : (tp === 'in_0' || tp === 'in' || !tp);
                if (!isFlowPin) return;

                if (c.source && c.source.startsWith('terminal_left')) {
                    conds.push('true');
                } else if (sortedIndex[c.source] !== undefined) {
                    conds.push(`out_r${rungIdx}_b${sortedIndex[c.source]}`);
                }
            });
            return conds.length > 0 ? `(${conds.join(' || ')})` : 'true';
        };

        // 3. Emit C code in topological order
        sorted.forEach((blockId, idx) => {
            const b = nodeMap[blockId];
            const type = b.type || '';
            const data = b.data || {};
            const subType = data.subType || (type === 'Contact' ? 'NO' : 'Normal');
            const bOut = `out_r${rungIdx}_b${idx}`;
            const inExpr = getInExpr(blockId, type);

            out += `    bool ${bOut} = false;\n`;

            if (type === 'Contact') {
                const varName = ((data.values?.var || data.instanceName) + '').replace(/[🌍🏠⊞⊡⊟]/g, '').trim() || null;
                if (varName) {
                    const v = resolveVar(varName);
                    if (subType === 'NC' || subType === 'Falling') {
                        out += `    ${bOut} = ${inExpr} && !${v};\n`;
                    } else {
                        out += `    ${bOut} = ${inExpr} && ${v};\n`;
                    }
                } else {
                    out += `    ${bOut} = ${inExpr}; // Contact: no variable assigned\n`;
                }

            } else if (type === 'Coil') {
                const varName = ((data.values?.coil || data.instanceName) + '').replace(/[🌍🏠⊞⊡⊟]/g, '').trim() || null;
                out += `    ${bOut} = ${inExpr};\n`;
                if (varName) {
                    const v = resolveVar(varName);
                    if (subType === 'Negated') {
                        out += `    ${v} = !(${bOut});\n`;
                    } else if (subType === 'Set') {
                        out += `    if (${bOut}) { ${v} = true; }\n`;
                    } else if (subType === 'Reset') {
                        out += `    if (${bOut}) { ${v} = false; }\n`;
                    } else {
                        out += `    ${v} = ${bOut};\n`;
                    }
                }

            } else {
                // ── Function Block (standard or user-defined) ──────────────────
                const instName = data.instanceName || type;
                const callTarget = getCallTarget(instName);
                const inputPins = FB_INPUTS[type] || (stdFunctions[type] ? stdFunctions[type].inputs : []);

                // Determine output pin names for this block type so we can separate
                // write-back assignments (post-call) from input assignments (pre-call)
                let outputPinNames = new Set(FB_OUTPUTS[type] || []);
                if (data.customData?.content?.variables) {
                    data.customData.content.variables
                        .filter(v => v.class === 'Output')
                        .forEach(v => outputPinNames.add(v.name));
                }

                // Step 1: assign static pin values entered in the block's INPUT fields
                //         Skip output pins — those are written back after the call
                if (data.values) {
                    Object.entries(data.values).forEach(([pinName, val]) => {
                        if (outputPinNames.has(pinName)) return; // handled post-call
                        const resolved = resolveVal(val);
                        if (resolved !== null && resolved !== undefined) {
                            out += `    ${callTarget}.${pinName} = ${resolved};\n`;
                        }
                    });
                }

                // Step 2: assign non-trigger inputs that arrive via wire connections
                (rung.connections || []).forEach(c => {
                    if (c.target !== blockId) return;
                    const tp = c.targetPin;
                    // Skip the power-flow (trigger) handle
                    if (!tp || tp === 'in_0' || tp === 'in') return;
                    const pinIdx = parseInt(tp.split('_')[1]);
                    if (isNaN(pinIdx)) return;
                    const pinName = inputPins[pinIdx];
                    if (!pinName) return;
                    if (c.source && c.source.startsWith('terminal_left')) {
                        out += `    ${callTarget}.${pinName} = true;\n`;
                    } else if (sortedIndex[c.source] !== undefined) {
                        out += `    ${callTarget}.${pinName} = out_r${rungIdx}_b${sortedIndex[c.source]};\n`;
                    }
                });

                // Step 3: set the trigger (power-flow) input — always from inExpr
                const triggerPin = FB_TRIGGER_PIN[type] || (inputPins.length > 0 ? inputPins[0] : null);
                if (triggerPin) {
                    out += `    ${callTarget}.${triggerPin} = ${inExpr};\n`;
                }

                // Call the FB execute function
                if (stdFunctions[type]?.hasTime) {
                    if (stdFunctions[type]?.isFB !== false || Object.keys(FB_INPUTS).includes(type)) {
                        out += `    ${type}_Call(&${callTarget}, us_tick);\n`;
                    } else {
                        out += `    ${bOut} = ${type}_Call(${inExpr}); // Unhandled function with time\n`;
                    }
                } else {
                    if (stdFunctions[type]?.isFB !== false || Object.keys(FB_INPUTS).includes(type)) { // Standard blocks or FBs
                        out += `    ${type}_Call(&${callTarget}); // FBs handle their own execution\n`;
                    } else {
                        // Regular function call transpilation fallback
                        const funcArgs = [inExpr];
                        for (let i = 1; i < inputPins.length; i++) {
                            funcArgs.push(`${callTarget}.${inputPins[i]}`);
                        }
                        out += `    ${bOut} = ${type}_Call(${funcArgs.join(', ')});\n`;
                    }
                }

                // Check and propagate EN -> ENO correctly for regular FBs, or use Q-output
                const qOutput = FB_Q_OUTPUT[type] || (triggerPin === 'EN' ? 'ENO' : 'Q');
                if (qOutput === 'ENO' && triggerPin === 'EN') {
                    // Implicit power flow
                    out += `    ${bOut} = ${callTarget}.EN;\n`;
                } else if (qOutput) {
                    out += `    ${bOut} = ${callTarget}.${qOutput};\n`;
                } else {
                    out += `    ${bOut} = false;\n`;
                }

                // Step 4: output pin write-back — all pins, to assigned var or shadow tracking var
                const safeInst = instName.trim().replace(/\s+/g, '_');
                outputPinNames.forEach(pinName => {
                    const rawVal = data.values?.[pinName];
                    const varStr = rawVal ? (rawVal + '').replace(/[🌍🏠⊞⊡⊟]/g, '').trim() : '';
                    if (varStr && /^[A-Za-z_][A-Za-z0-9_]*(\[[^\]]*\]|\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(varStr)) {
                        out += `    ${resolveVar(varStr)} = ${callTarget}.${pinName};\n`;
                    } else {
                        // No assignment → shadow tracking variable (declared by collectShadowVars)
                        out += `    prog_${parentName}_out_${safeInst}_${pinName} = ${callTarget}.${pinName};\n`;
                    }
                });
            }
        });
    });

    return out;
};

const mapType = (iecType) => {
    const typeMap = {
        'BOOL': 'bool',
        'SINT': 'int8_t',
        'INT': 'int16_t',
        'DINT': 'int32_t',
        'LINT': 'int64_t',
        'USINT': 'uint8_t',
        'UINT': 'uint16_t',
        'UDINT': 'uint32_t',
        'ULINT': 'uint64_t',
        'REAL': 'float',
        'LREAL': 'double',
        'BYTE': 'uint8_t',
        'WORD': 'uint16_t',
        'DWORD': 'uint32_t',
        'LWORD': 'uint64_t',
        'TIME': 'uint32_t',
        'STRING': 'char*',
        'VOID': 'void'
    };
    return typeMap[iecType] || iecType; // Fallback to custom name
};

const transpileDataType = (dt) => {
    let code = '';
    if (dt.type === 'Enumerated') {
        code += `typedef enum {\n`;
        dt.content.values.forEach((val, i) => {
            code += `    ${val.name}${val.value !== undefined && val.value !== '' ? ` = ${val.value}` : ''}${i < dt.content.values.length - 1 ? ',' : ''}\n`;
        });
        code += `} ${dt.name};\n\n`;
    } else if (dt.type === 'Structure') {
        code += `typedef struct {\n`;
        dt.content.members.forEach(member => {
            code += `    ${mapType(member.type)} ${member.name};\n`;
        });
        code += `} ${dt.name};\n\n`;
    } else if (dt.type === 'Array') {
        const sizes = dt.content.dimensions.map(d => `[${parseInt(d.max) - parseInt(d.min) + 1}]`).join('');
        code += `typedef ${mapType(dt.content.baseType)} ${dt.name}${sizes};\n\n`;
    }
    return code;
};
