export const transpileToC = (projectStructure, standardHeaders = []) => {
    let stdFunctions = {};
    let customIncludes = ``;

    standardHeaders.forEach(([filename, content]) => {
        customIncludes += `#include "${filename}"\n`;
        const regex = /void\s+([A-Za-z0-9_]+)_Call\s*\(([^)]+)\)/g;
        let match;
        while ((match = regex.exec(content)) !== null) {
            const blockType = match[1];
            const params = match[2];
            stdFunctions[blockType] = { hasTime: params.includes('TIME') };
        }
    });

    const resolveInitialValue = (val, type) => {
        if (val !== undefined && val !== null && val !== '') {
            if (type === 'BOOL') return val.toString().toLowerCase() === 'true' || val === '1';
            if (['STRING'].includes(type)) return val.toString().replace(/^"|"$/g, '');
            return Number(val) || 0;
        }
        if (type === 'BOOL') return false;
        if (['STRING'].includes(type)) return "";
        return 0;
    };

    let header = `// Autogenerated by KronEditor CTranspiler
#ifndef PLC_H
#define PLC_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
${customIncludes}

extern volatile uint64_t us_tick;

`;

    let source = `// Autogenerated by KronEditor CTranspiler\n#include "plc.h"\n\n#if defined(__linux__) || defined(__APPLE__)\n#include <time.h>\n#include <unistd.h>\n#elif defined(_WIN32)\nvoid Sleep(unsigned long ms); /* kernel32.dll, no windows.h needed */\n#endif\n\n`;

    let variableTable = {
        dataTypes: {},
        globalVars: {},
        programs: {}
    };

    // 1. Data Types (Header only)
    if (projectStructure.dataTypes && projectStructure.dataTypes.length > 0) {
        header += `// --- DATA TYPES ---\n`;
        projectStructure.dataTypes.forEach(dt => {
            header += transpileDataType(dt);
            // Record structured mapping
            variableTable.dataTypes[dt.name] = {
                type: dt.type,
                content: dt.content
            };
        });
    }

    // 2. Global Variables
    const config = projectStructure.resources?.find(r => r.id === 'res_config');
    if (config && config.content.globalVars && config.content.globalVars.length > 0) {
        header += `// --- GLOBAL VARIABLES ---\n`;
        config.content.globalVars.forEach(v => {
            let initVal = v.initialValue ? ` = ${v.initialValue}` : '';
            if (v.type === 'STRING' && v.initialValue) initVal = ` = "${v.initialValue}"`;
            header += `${mapType(v.type)} ${v.name}${initVal};\n`;
            variableTable.globalVars[v.name] = {
                type: v.type,
                initialValue: resolveInitialValue(v.initialValue, v.type)
            };
        });
        header += `\n`;
    }

    // 3. Function Blocks (State Structures)
    if (projectStructure.functionBlocks && projectStructure.functionBlocks.length > 0) {
        header += `// --- FUNCTION BLOCK STATES ---\n`;
        projectStructure.functionBlocks.forEach(fb => {
            header += `typedef struct {\n`;
            fb.content.variables.forEach(v => {
                header += `    ${mapType(v.type)} ${v.name};\n`;
            });
            header += `} ${fb.name};\n\n`;
        });
    }

    // 4. Function and Program Signatures
    header += `// --- SIGNATURES ---\n`;

    if (projectStructure.functions) {
        projectStructure.functions.forEach(fn => {
            const retType = mapType(fn.returnType || 'VOID');
            let fnName = (fn.name || '').trim().replace(/\s+/g, '_');
            header += `static inline ${retType} ${fnName}();\n`;
        });
    }

    if (projectStructure.functionBlocks) {
        projectStructure.functionBlocks.forEach(fb => {
            let fbName = (fb.name || '').trim().replace(/\s+/g, '_');
            header += `static inline void ${fbName}_Execute(${fbName} *instance);\n`;
        });
    }

    if (projectStructure.programs) {
        projectStructure.programs.forEach(prog => {
            let progName = (prog.name || '').trim().replace(/\s+/g, '_');
            header += `static inline void ${progName}();\n`;
        });
    }

    // Collect global variable names (used by LD transpiler to skip prog_ prefix)
    const globalVarNames = (config?.content?.globalVars || [])
        .map(v => (v.name || '').trim().replace(/\s+/g, '_'));

    header += `\n// --- IMPLEMENTATIONS ---\n`;

    if (projectStructure.functions) {
        header += `// --- FUNCTIONS ---\n`;
        projectStructure.functions.forEach(fn => {
            header += transpilePOUSource(fn, 'function', stdFunctions, fn.name, globalVarNames);
        });
    }

    if (projectStructure.functionBlocks) {
        header += `// --- FUNCTION BLOCKS ---\n`;
        projectStructure.functionBlocks.forEach(fb => {
            header += transpilePOUSource(fb, 'function_block', stdFunctions, fb.name, globalVarNames);
        });
    }

    if (projectStructure.programs) {
        header += `// --- PROGRAMS ---\n`;
        projectStructure.programs.forEach(prog => {
            let progName = (prog.name || '').trim().replace(/\s+/g, '_');

            variableTable.programs[progName] = { variables: {} };

            // Allocate static program instances of FBs if they exist
            prog.content.variables.forEach(v => {
                let vName = (v.name || '').trim().replace(/\s+/g, '_');
                if (isFBType(v.type, projectStructure) || stdFunctions[v.type]) {
                    header += `${v.type} prog_${progName}_inst_${vName};\n`;
                } else {
                    // Global internal variables for simple programs
                    header += `${mapType(v.type)} prog_${progName}_${vName};\n`;
                }

                variableTable.programs[progName].variables[vName] = {
                    type: v.type,
                    c_symbol: (isFBType(v.type, projectStructure) || stdFunctions[v.type]) ? `prog_${progName}_inst_${vName}` : `prog_${progName}_${vName}`,
                    initialValue: resolveInitialValue(v.initialValue, v.type)
                };
            });
            header += transpilePOUSource(prog, 'program', stdFunctions, progName, globalVarNames);
        });
    }

    header += `\n#endif // PLC_H\n`;

    // --- 5. DETERMINISTIC SCAN LOOP ---
    source += generateMainLoop(projectStructure, config);

    return { header, source, variableTable };
};

const isFBType = (type, structure) => {
    return structure.functionBlocks?.some(fb => fb.name === type);
};

const mapIECtoTimeUs = (iecTimeStr) => {
    if (!iecTimeStr) return 10000;
    const str = iecTimeStr.toUpperCase().replace('T#', '').replace('TIME#', '');
    if (str.endsWith('MS')) return parseInt(str.replace('MS', '')) * 1000;
    if (str.endsWith('US')) return parseInt(str.replace('US', ''));
    if (str.endsWith('S')) return parseInt(str.replace('S', '')) * 1000000;
    return 10000; // Default 10000us (10ms)
};



const generateMainLoop = (projectStructure, config) => {
    let mainSrc = `\n// --- DETERMINISTIC SCAN LOOP ---\n`;

    mainSrc += `\n// Global Tick Variable\n`;
    mainSrc += `#if defined(__linux__) || defined(__APPLE__) || defined(_WIN32)\n`;
    mainSrc += `// Defined here for simulation\n`;
    mainSrc += `extern volatile uint64_t us_tick;\n`;
    mainSrc += `volatile uint64_t us_tick = 0;\n`;
    mainSrc += `volatile int plc_stop = 0;\n`;
    mainSrc += `#else\n`;
    mainSrc += `// For Cortex-M4 and bare-metal targets, us_tick MUST be defined\n`;
    mainSrc += `// and incremented in your hardware timer interrupt.\n`;
    mainSrc += `// Example: volatile uint64_t us_tick = 0; void Timer_Handler(void) { us_tick += 10; }\n`;
    mainSrc += `#endif\n\n`;
    // Provide a Cortex-M4 compatible fallback main loop
    mainSrc += `#if defined(__linux__) || defined(__APPLE__) || defined(_WIN32)\n`;
    mainSrc += `int main() {\n`;

    // 1. Tick trackers (platform-specific sleep setup)
    mainSrc += `#if defined(__linux__) || defined(__APPLE__)\n`;
    mainSrc += `    struct timespec req, rem;\n`;
    mainSrc += `    req.tv_sec = 0;\n`;
    mainSrc += `    req.tv_nsec = 1000000; // 1ms\n`;
    mainSrc += `#endif\n\n`;

    // 2. Discover Task mappings and Instances
    let programTasks = [];

    if (config && config.content.instances) {
        config.content.instances.forEach(inst => {
            const task = config.content.tasks?.find(t => t.name === inst.task);
            let pName = (inst.program || '').trim().replace(/\s+/g, '_');
            if (task) {
                programTasks.push({
                    name: pName,
                    intervalUs: mapIECtoTimeUs(task.interval)
                });
            } else {
                programTasks.push({ name: pName, intervalUs: 10000 }); // Default 10ms
            }
        });
    } else if (projectStructure.programs) {
        projectStructure.programs.forEach(p => {
            let pName = (p.name || '').trim().replace(/\s+/g, '_');
            programTasks.push({ name: pName, intervalUs: 10000 });
        });
    }

    mainSrc += `    while(!plc_stop) {\n`;

    // 3. Scan logic
    programTasks.forEach(pt => {
        mainSrc += `        if (us_tick % ${pt.intervalUs} == 0) {\n`;
        mainSrc += `            ${pt.name}();\n`;
        mainSrc += `        }\n`;
    });

    // 4. Advance time (platform-specific 1ms sleep)
    mainSrc += `#if defined(__linux__) || defined(__APPLE__)\n`;
    mainSrc += `        nanosleep(&req, &rem);\n`;
    mainSrc += `#elif defined(_WIN32)\n`;
    mainSrc += `        Sleep(1);\n`;
    mainSrc += `#endif\n`;
    mainSrc += `        us_tick += 1000;\n`; // Advance 1000us (1ms)
    mainSrc += `    }\n`;
    mainSrc += `    return 0;\n}\n`;

    mainSrc += `#else\n\n`;
    mainSrc += `// Bare-metal / Cortex-M4 execution engine\n`;
    mainSrc += `// You must provide a timer to increment us_tick\n`;
    mainSrc += `void PLC_Run() {\n`;
    programTasks.forEach(pt => {
        mainSrc += `    if (us_tick % ${pt.intervalUs} == 0) {\n`;
        mainSrc += `        ${pt.name}();\n`;
        mainSrc += `    }\n`;
    });
    mainSrc += `}\n\n`;
    mainSrc += `#endif\n`;

    return mainSrc;
};

const transpilePOUSource = (pou, category, stdFunctions = {}, parentName = '', globalVarNames = []) => {
    let src = ``;
    let safeName = (pou.name || '').trim().replace(/\s+/g, '_');
    let sig = `static inline void ${safeName}()`;

    if (category === 'function') {
        const retType = mapType(pou.returnType || 'VOID');
        sig = `static inline ${retType} ${safeName}()`;
    } else if (category === 'function_block') {
        sig = `static inline void ${safeName}_Execute(${safeName} *instance)`;
    }

    src += `${sig} {\n`;

    if (pou.type === 'ST') {
        // Build variable name map: IEC identifier → C symbol
        const varMap = {};
        (pou.content.variables || []).forEach(v => {
            const vName = (v.name || '').trim().replace(/\s+/g, '_');
            if (!vName) return;
            if (globalVarNames.includes(vName)) {
                varMap[vName] = vName; // global vars: no prefix
            } else if (category === 'program') {
                const isFB = stdFunctions[v.type] !== undefined;
                varMap[vName] = isFB
                    ? `prog_${parentName}_inst_${vName}`
                    : `prog_${parentName}_${vName}`;
            } else if (category === 'function_block') {
                varMap[vName] = `instance->${vName}`;
            } else {
                varMap[vName] = vName;
            }
        });
        src += transpileSTLogics(pou.content.code, stdFunctions, parentName, category, varMap);
    } else if (pou.type === 'LD') {
        src += transpileLDLogics(pou.content.rungs, stdFunctions, safeName, category, globalVarNames);
    }

    src += `}\n\n`;
    return src;
};

// --- LD Block Type Definitions (mirrors blockConfig in RungContainer) ---
// Trigger (first/power-flow) input pin for each standard FB type
const FB_TRIGGER_PIN = {
    // Timers
    'TON': 'IN', 'TOF': 'IN', 'TP': 'IN',
    // Counters
    'CTU': 'CU', 'CTD': 'CD', 'CTUD': 'CU',
    // Edge detectors
    'R_TRIG': 'CLK', 'F_TRIG': 'CLK',
    // Bistable
    'RS': 'S', 'SR': 'S1',
    // Comparison / Arithmetic / Math / Bitwise — EN is the power-flow input
    'GT': 'EN', 'GE': 'EN', 'EQ': 'EN', 'NE': 'EN', 'LE': 'EN', 'LT': 'EN',
    'ADD': 'EN', 'SUB': 'EN', 'MUL': 'EN', 'DIV': 'EN', 'MOD': 'EN', 'MOVE': 'EN',
    'ABS': 'EN', 'SQRT': 'EN', 'EXPT': 'EN', 'MAX': 'EN', 'MIN': 'EN', 'LIMIT': 'EN',
    'BAND': 'EN', 'BOR': 'EN', 'BXOR': 'EN', 'BNOT': 'EN',
    'SHL': 'EN', 'SHR': 'EN', 'ROL': 'EN', 'ROR': 'EN'
};

// Primary boolean output pin for downstream power flow
const FB_Q_OUTPUT = {
    // Timers
    'TON': 'Q', 'TOF': 'Q', 'TP': 'Q',
    // Counters
    'CTU': 'Q', 'CTD': 'Q', 'CTUD': 'QU',
    // Edge detectors
    'R_TRIG': 'Q', 'F_TRIG': 'Q',
    // Bistable
    'RS': 'Q1', 'SR': 'Q1',
    // Comparison: ENO = EN && (result) — acts as conditional power flow
    'GT': 'ENO', 'GE': 'ENO', 'EQ': 'ENO', 'NE': 'ENO', 'LE': 'ENO', 'LT': 'ENO',
    // Arithmetic / Math / Bitwise: ENO = EN — passes power through
    'ADD': 'ENO', 'SUB': 'ENO', 'MUL': 'ENO', 'DIV': 'ENO', 'MOD': 'ENO', 'MOVE': 'ENO',
    'ABS': 'ENO', 'SQRT': 'ENO', 'EXPT': 'ENO', 'MAX': 'ENO', 'MIN': 'ENO', 'LIMIT': 'ENO',
    'BAND': 'ENO', 'BOR': 'ENO', 'BXOR': 'ENO', 'BNOT': 'ENO',
    'SHL': 'ENO', 'SHR': 'ENO', 'ROL': 'ENO', 'ROR': 'ENO'
};

// Ordered input pin names for each standard FB type (index matches in_0, in_1, ...)
const FB_INPUTS = {
    'TON':    ['IN', 'PT'],
    'TOF':    ['IN', 'PT'],
    'TP':     ['IN', 'PT'],
    'CTU':    ['CU', 'R', 'PV'],
    'CTD':    ['CD', 'LD', 'PV'],
    'CTUD':   ['CU', 'CD', 'R', 'LD', 'PV'],
    'R_TRIG': ['CLK'],
    'F_TRIG': ['CLK'],
    'RS':     ['S', 'R1'],
    'SR':     ['S1', 'R'],
    // Comparison
    'GT': ['EN', 'IN1', 'IN2'], 'GE': ['EN', 'IN1', 'IN2'], 'EQ': ['EN', 'IN1', 'IN2'],
    'NE': ['EN', 'IN1', 'IN2'], 'LE': ['EN', 'IN1', 'IN2'], 'LT': ['EN', 'IN1', 'IN2'],
    // Arithmetic
    'ADD':  ['EN', 'IN1', 'IN2'], 'SUB':  ['EN', 'IN1', 'IN2'],
    'MUL':  ['EN', 'IN1', 'IN2'], 'DIV':  ['EN', 'IN1', 'IN2'],
    'MOD':  ['EN', 'IN1', 'IN2'], 'MOVE': ['EN', 'IN'],
    // Math
    'ABS':   ['EN', 'IN'],         'SQRT':  ['EN', 'IN'],
    'EXPT':  ['EN', 'IN', 'EXP'],
    'MAX':   ['EN', 'IN1', 'IN2'], 'MIN':   ['EN', 'IN1', 'IN2'],
    'LIMIT': ['EN', 'IN', 'MN', 'MX'],
    // Bitwise
    'BAND': ['EN', 'IN1', 'IN2'], 'BOR':  ['EN', 'IN1', 'IN2'],
    'BXOR': ['EN', 'IN1', 'IN2'], 'BNOT': ['EN', 'IN'],
    'SHL':  ['EN', 'IN', 'N'],    'SHR':  ['EN', 'IN', 'N'],
    'ROL':  ['EN', 'IN', 'N'],    'ROR':  ['EN', 'IN', 'N']
};

const transpileSTLogics = (code, stdFunctions = {}, parentName = '', category = 'program', varMap = {}) => {
    if (!code) return `    // ST Implementation Empty\n`;

    // Split on actual newlines or escaped \n sequences (both may appear depending on storage)
    const lines = code.split(/\r?\n|\\n/);
    let out = '';
    let indentLevel = 1; // 1 = inside function body (4 spaces)

    const indent = () => '    '.repeat(indentLevel);

    // Substitute known variable names with their C equivalents
    const resolveVarsInExpr = (expr) => {
        const sortedNames = Object.keys(varMap).sort((a, b) => b.length - a.length);
        let result = expr;
        sortedNames.forEach(name => {
            result = result.replace(new RegExp(`\\b${name}\\b`, 'g'), varMap[name]);
        });
        return result;
    };

    const transformExpr = (expr) => {
        let result = expr
            .replace(/:=/g, '=')
            .replace(/\bAND\b/g, '&&')
            .replace(/\bOR\b/g, '||')
            .replace(/\bNOT\b/g, '!')
            .replace(/\bMOD\b/g, '%')
            .replace(/\bXOR\b/g, '^')
            .replace(/\bTRUE\b/gi, 'true')
            .replace(/\bFALSE\b/gi, 'false');
        return resolveVarsInExpr(result);
    };

    lines.forEach(line => {
        const trimmed = line.trim();
        if (!trimmed) return;

        // ── Block closing keywords ────────────────────────────────────────
        if (/^END_IF\s*;?$/i.test(trimmed)) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}}\n`;
            return;
        }
        if (/^END_FOR\s*;?$/i.test(trimmed)) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}}\n`;
            return;
        }
        if (/^END_WHILE\s*;?$/i.test(trimmed)) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}}\n`;
            return;
        }

        // ── ELSIF / ELSE IF (check before standalone ELSE) ────────────────
        const elsifMatch = trimmed.match(/^(?:ELSIF|ELSE\s+IF)\s+(.+?)\s+THEN\s*;?\s*$/i);
        if (elsifMatch) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}} else if (${transformExpr(elsifMatch[1])}) {\n`;
            indentLevel++;
            return;
        }

        // ── ELSE ──────────────────────────────────────────────────────────
        if (/^ELSE\s*;?\s*$/i.test(trimmed)) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}} else {\n`;
            indentLevel++;
            return;
        }

        // ── IF ... THEN ───────────────────────────────────────────────────
        const ifMatch = trimmed.match(/^IF\s+(.+?)\s+THEN\s*;?\s*$/i);
        if (ifMatch) {
            out += `${indent()}if (${transformExpr(ifMatch[1])}) {\n`;
            indentLevel++;
            return;
        }

        // ── FOR ... TO ... BY ... DO (BY clause first — more specific) ────
        const forByMatch = trimmed.match(/^FOR\s+(\w+)\s*:=\s*(.+?)\s+TO\s+(.+?)\s+BY\s+(.+?)\s+DO\s*;?\s*$/i);
        if (forByMatch) {
            const [, vn, start, end, step] = forByMatch;
            const cv = varMap[vn] || vn;
            out += `${indent()}for (${cv} = ${transformExpr(start)}; ${cv} <= ${transformExpr(end)}; ${cv} += ${transformExpr(step)}) {\n`;
            indentLevel++;
            return;
        }

        // ── FOR ... TO ... DO ─────────────────────────────────────────────
        const forMatch = trimmed.match(/^FOR\s+(\w+)\s*:=\s*(.+?)\s+TO\s+(.+?)\s+DO\s*;?\s*$/i);
        if (forMatch) {
            const [, vn, start, end] = forMatch;
            const cv = varMap[vn] || vn;
            out += `${indent()}for (${cv} = ${transformExpr(start)}; ${cv} <= ${transformExpr(end)}; ${cv}++) {\n`;
            indentLevel++;
            return;
        }

        // ── WHILE ... DO ──────────────────────────────────────────────────
        const whileMatch = trimmed.match(/^WHILE\s+(.+?)\s+DO\s*;?\s*$/i);
        if (whileMatch) {
            out += `${indent()}while (${transformExpr(whileMatch[1])}) {\n`;
            indentLevel++;
            return;
        }

        // ── REPEAT (do-while start) ───────────────────────────────────────
        if (/^REPEAT\s*;?\s*$/i.test(trimmed)) {
            out += `${indent()}do {\n`;
            indentLevel++;
            return;
        }

        // ── UNTIL (do-while end) ──────────────────────────────────────────
        const untilMatch = trimmed.match(/^UNTIL\s+(.+?)\s*;?\s*$/i);
        if (untilMatch) {
            indentLevel = Math.max(1, indentLevel - 1);
            out += `${indent()}} while (!(${transformExpr(untilMatch[1])}));\n`;
            return;
        }

        // ── EXIT → break ──────────────────────────────────────────────────
        if (/^EXIT\s*;?\s*$/i.test(trimmed)) {
            out += `${indent()}break;\n`;
            return;
        }

        // ── RETURN ────────────────────────────────────────────────────────
        if (/^RETURN\b/i.test(trimmed)) {
            const retVal = trimmed.replace(/^RETURN\s*/i, '').replace(/;$/, '').trim();
            out += `${indent()}return${retVal ? ` ${transformExpr(retVal)}` : ''};\n`;
            return;
        }

        // ── Regular statement (assignment, function call, etc.) ───────────
        let cl = transformExpr(trimmed);
        if (!cl.endsWith(';')) cl += ';';
        out += `${indent()}${cl}\n`;
    });

    return out || `    // ST parsing placeholder\n`;
};

const transpileLDLogics = (rungs, stdFunctions = {}, parentName = '', category = 'program', globalVarNames = []) => {
    if (!rungs || rungs.length === 0) return `    // LD Implementation Empty\n`;

    let out = '';

    // Resolve a variable/signal name to its C symbol, respecting scope
    const resolveVar = (varName) => {
        if (!varName) return null;
        const v = varName.trim().replace(/\s+/g, '_');
        if (category === 'program') {
            // Global variables are declared without prefix; local program vars get prog_ prefix
            return globalVarNames.includes(v) ? v : `prog_${parentName}_${v}`;
        }
        if (category === 'function_block') return `instance->${v}`;
        return v;
    };

    // Resolve a value string: IEC time literal → us integer, numeric → as-is, identifier → scoped var
    const resolveVal = (val) => {
        if (!val && val !== 0) return null;
        const s = val.toString().trim();
        if (!s) return null;
        if (s.toUpperCase().startsWith('T#') || s.toUpperCase().startsWith('TIME#')) {
            return mapIECtoTimeUs(s).toString();
        }
        // Numeric literal (int, float, hex)
        if (/^-?[0-9][0-9a-fA-FxX.]*$/.test(s)) return s;
        // Boolean literals
        if (s === 'true' || s === 'false') return s;
        // Otherwise treat as variable reference
        return resolveVar(s);
    };

    // Get the C call-target for an FB instance
    const getCallTarget = (instName) => {
        const i = (instName || '').trim().replace(/\s+/g, '_');
        if (category === 'program') return `prog_${parentName}_inst_${i}`;
        if (category === 'function_block') return `instance->${i}`;
        return i;
    };

    rungs.forEach((rung, rungIdx) => {
        out += `    // Rung ${rungIdx}\n`;

        if (!rung.blocks || rung.blocks.length === 0) {
            out += `    // Empty Rung\n`;
            return;
        }

        // 1. Build adjacency graph (block-to-block only; terminal connections excluded)
        const adjacency = {};
        const incoming = {};
        const nodeMap = {};

        rung.blocks.forEach(b => {
            nodeMap[b.id] = b;
            adjacency[b.id] = [];
            incoming[b.id] = 0;
        });

        // Track unique source→target pairs so duplicate connections don't skew in-degree
        const addedEdges = new Set();
        (rung.connections || []).forEach(c => {
            const edgeKey = `${c.source}->${c.target}`;
            if (
                adjacency[c.source] !== undefined &&
                incoming[c.target] !== undefined &&
                !addedEdges.has(edgeKey)
            ) {
                addedEdges.add(edgeKey);
                adjacency[c.source].push(c.target);
                incoming[c.target]++;
            }
        });

        // 2. Topological sort (Kahn's algorithm)
        const queue = [];
        const sorted = [];
        Object.keys(incoming).forEach(id => {
            if (incoming[id] === 0) queue.push(id);
        });
        while (queue.length > 0) {
            const curr = queue.shift();
            sorted.push(curr);
            adjacency[curr].forEach(child => {
                incoming[child]--;
                if (incoming[child] === 0) queue.push(child);
            });
        }
        // Append any blocks not reached (disconnected sub-graphs / cycles)
        rung.blocks.forEach(b => {
            if (!sorted.includes(b.id)) sorted.push(b.id);
        });

        // Index map: blockId → position in sorted array
        const sortedIndex = {};
        sorted.forEach((id, idx) => { sortedIndex[id] = idx; });

        // Build power-flow (inExpr) for a block:
        //   Contact / Coil use handle id "in"
        //   FB first input uses "in_0"
        //   Multiple parallel paths converging are OR'd
        const getInExpr = (blockId, blockType) => {
            const isSimple = blockType === 'Contact' || blockType === 'Coil';
            const conds = [];
            (rung.connections || []).forEach(c => {
                if (c.target !== blockId) return;
                // Accept only the power-flow target handle
                const tp = c.targetPin;
                const isFlowPin = isSimple
                    ? (tp === 'in' || !tp)
                    : (tp === 'in_0' || tp === 'in' || !tp);
                if (!isFlowPin) return;

                if (c.source && c.source.startsWith('terminal_left')) {
                    conds.push('true');
                } else if (sortedIndex[c.source] !== undefined) {
                    conds.push(`out_r${rungIdx}_b${sortedIndex[c.source]}`);
                }
            });
            return conds.length > 0 ? `(${conds.join(' || ')})` : 'true';
        };

        // 3. Emit C code in topological order
        sorted.forEach((blockId, idx) => {
            const b = nodeMap[blockId];
            const type = b.type || '';
            const data = b.data || {};
            const subType = data.subType || (type === 'Contact' ? 'NO' : 'Normal');
            const bOut = `out_r${rungIdx}_b${idx}`;
            const inExpr = getInExpr(blockId, type);

            out += `    bool ${bOut} = false;\n`;

            if (type === 'Contact') {
                const varName = data.values?.var || data.instanceName;
                if (varName) {
                    const v = resolveVar(varName);
                    if (subType === 'NC' || subType === 'Falling') {
                        out += `    ${bOut} = ${inExpr} && !${v};\n`;
                    } else {
                        out += `    ${bOut} = ${inExpr} && ${v};\n`;
                    }
                } else {
                    out += `    ${bOut} = ${inExpr}; // Contact: no variable assigned\n`;
                }

            } else if (type === 'Coil') {
                const varName = data.values?.coil || data.instanceName;
                out += `    ${bOut} = ${inExpr};\n`;
                if (varName) {
                    const v = resolveVar(varName);
                    if (subType === 'Negated') {
                        out += `    ${v} = !(${bOut});\n`;
                    } else if (subType === 'Set') {
                        out += `    if (${bOut}) { ${v} = true; }\n`;
                    } else if (subType === 'Reset') {
                        out += `    if (${bOut}) { ${v} = false; }\n`;
                    } else {
                        out += `    ${v} = ${bOut};\n`;
                    }
                }

            } else {
                // ── Function Block (standard or user-defined) ──────────────────
                const instName = data.instanceName || type;
                const callTarget = getCallTarget(instName);
                const inputPins = FB_INPUTS[type] || [];

                // Step 1: assign static pin values entered in the block's input fields
                //         (these are overridden below for the trigger pin)
                if (data.values) {
                    Object.entries(data.values).forEach(([pinName, val]) => {
                        const resolved = resolveVal(val);
                        if (resolved !== null && resolved !== undefined) {
                            out += `    ${callTarget}.${pinName} = ${resolved};\n`;
                        }
                    });
                }

                // Step 2: assign non-trigger inputs that arrive via wire connections
                (rung.connections || []).forEach(c => {
                    if (c.target !== blockId) return;
                    const tp = c.targetPin;
                    // Skip the power-flow (trigger) handle
                    if (!tp || tp === 'in_0' || tp === 'in') return;
                    const pinIdx = parseInt(tp.split('_')[1]);
                    if (isNaN(pinIdx)) return;
                    const pinName = inputPins[pinIdx];
                    if (!pinName) return;
                    if (c.source && c.source.startsWith('terminal_left')) {
                        out += `    ${callTarget}.${pinName} = true;\n`;
                    } else if (sortedIndex[c.source] !== undefined) {
                        out += `    ${callTarget}.${pinName} = out_r${rungIdx}_b${sortedIndex[c.source]};\n`;
                    }
                });

                // Step 3: set the trigger (power-flow) input — always from inExpr
                const trigPin = FB_TRIGGER_PIN[type] || (data.executionControl ? 'EN' : null);
                if (trigPin) {
                    out += `    ${callTarget}.${trigPin} = ${inExpr};\n`;
                }

                // Step 4: call the block function
                if (stdFunctions[type]) {
                    const timeArg = stdFunctions[type].hasTime ? ', us_tick' : '';
                    out += `    ${type}_Call(&${callTarget}${timeArg});\n`;
                } else {
                    out += `    ${type}_Execute(&${callTarget});\n`;
                }

                // Step 5: read Q output for downstream power flow
                const qPin = FB_Q_OUTPUT[type] || 'ENO';
                out += `    ${bOut} = ${callTarget}.${qPin};\n`;
            }
        });
    });

    return out;
};

const mapType = (iecType) => {
    const typeMap = {
        'BOOL': 'bool',
        'SINT': 'int8_t',
        'INT': 'int16_t',
        'DINT': 'int32_t',
        'LINT': 'int64_t',
        'USINT': 'uint8_t',
        'UINT': 'uint16_t',
        'UDINT': 'uint32_t',
        'ULINT': 'uint64_t',
        'REAL': 'float',
        'LREAL': 'double',
        'BYTE': 'uint8_t',
        'WORD': 'uint16_t',
        'DWORD': 'uint32_t',
        'LWORD': 'uint64_t',
        'TIME': 'uint32_t',
        'STRING': 'char*',
        'VOID': 'void'
    };
    return typeMap[iecType] || iecType; // Fallback to custom name
};

const transpileDataType = (dt) => {
    let code = '';
    if (dt.type === 'Enumerated') {
        code += `typedef enum {\n`;
        dt.content.values.forEach((val, i) => {
            code += `    ${val.identifier}${val.value ? ` = ${val.value}` : ''}${i < dt.content.values.length - 1 ? ',' : ''}\n`;
        });
        code += `} ${dt.name};\n\n`;
    } else if (dt.type === 'Structure') {
        code += `typedef struct {\n`;
        dt.content.members.forEach(member => {
            code += `    ${mapType(member.type)} ${member.name};\n`;
        });
        code += `} ${dt.name};\n\n`;
    } else if (dt.type === 'Array') {
        const totalSize = dt.content.dimensions.reduce((acc, dim) => acc * ((parseInt(dim.max) - parseInt(dim.min)) + 1), 1);
        code += `typedef struct {\n`;
        code += `    ${mapType(dt.content.baseType)} data[${totalSize}];\n`;
        code += `} ${dt.name};\n\n`;
    }
    return code;
};
