// Board definitions for KronEditor
// Each board family contains variants with hardware specs and pinout data

// Standard 40-pin Raspberry Pi GPIO Header (shared by Pi 3B, 3B+, 4B, 5, Zero 2W)
const RPI_40PIN_HEADER = [
  { pin: 1,  name: '3V3',      type: 'power',  color: '#ff6b35' },
  { pin: 2,  name: '5V',       type: 'power',  color: '#ff0000' },
  { pin: 3,  name: 'GPIO2',    type: 'gpio',   alt: 'SDA1 (I2C)', color: '#4a90d9' },
  { pin: 4,  name: '5V',       type: 'power',  color: '#ff0000' },
  { pin: 5,  name: 'GPIO3',    type: 'gpio',   alt: 'SCL1 (I2C)', color: '#4a90d9' },
  { pin: 6,  name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 7,  name: 'GPIO4',    type: 'gpio',   alt: 'GPCLK0', color: '#4caf50' },
  { pin: 8,  name: 'GPIO14',   type: 'gpio',   alt: 'TXD (UART)', color: '#9c27b0' },
  { pin: 9,  name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 10, name: 'GPIO15',   type: 'gpio',   alt: 'RXD (UART)', color: '#9c27b0' },
  { pin: 11, name: 'GPIO17',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 12, name: 'GPIO18',   type: 'gpio',   alt: 'PCM_CLK / PWM0', color: '#4caf50' },
  { pin: 13, name: 'GPIO27',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 14, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 15, name: 'GPIO22',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 16, name: 'GPIO23',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 17, name: '3V3',      type: 'power',  color: '#ff6b35' },
  { pin: 18, name: 'GPIO24',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 19, name: 'GPIO10',   type: 'gpio',   alt: 'MOSI (SPI0)', color: '#ff9800' },
  { pin: 20, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 21, name: 'GPIO9',    type: 'gpio',   alt: 'MISO (SPI0)', color: '#ff9800' },
  { pin: 22, name: 'GPIO25',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 23, name: 'GPIO11',   type: 'gpio',   alt: 'SCLK (SPI0)', color: '#ff9800' },
  { pin: 24, name: 'GPIO8',    type: 'gpio',   alt: 'CE0 (SPI0)', color: '#ff9800' },
  { pin: 25, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 26, name: 'GPIO7',    type: 'gpio',   alt: 'CE1 (SPI0)', color: '#ff9800' },
  { pin: 27, name: 'ID_SD',    type: 'special', alt: 'EEPROM SDA', color: '#607d8b' },
  { pin: 28, name: 'ID_SC',    type: 'special', alt: 'EEPROM SCL', color: '#607d8b' },
  { pin: 29, name: 'GPIO5',    type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 30, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 31, name: 'GPIO6',    type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 32, name: 'GPIO12',   type: 'gpio',   alt: 'PWM0', color: '#4caf50' },
  { pin: 33, name: 'GPIO13',   type: 'gpio',   alt: 'PWM1', color: '#4caf50' },
  { pin: 34, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 35, name: 'GPIO19',   type: 'gpio',   alt: 'PCM_FS / SPI1 MISO', color: '#4caf50' },
  { pin: 36, name: 'GPIO16',   type: 'gpio',   alt: 'SPI1 CE2', color: '#4caf50' },
  { pin: 37, name: 'GPIO26',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 38, name: 'GPIO20',   type: 'gpio',   alt: 'SPI1 MOSI', color: '#4caf50' },
  { pin: 39, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 40, name: 'GPIO21',   type: 'gpio',   alt: 'SPI1 SCLK', color: '#4caf50' },
];

// Raspberry Pi Pico pinout (RP2040)
const RPI_PICO_PINS = [
  { pin: 1,  name: 'GP0',     type: 'gpio',   alt: 'UART0 TX / I2C0 SDA / SPI0 RX', color: '#4caf50' },
  { pin: 2,  name: 'GP1',     type: 'gpio',   alt: 'UART0 RX / I2C0 SCL / SPI0 CS', color: '#4caf50' },
  { pin: 3,  name: 'GND',     type: 'ground', color: '#333333' },
  { pin: 4,  name: 'GP2',     type: 'gpio',   alt: 'I2C1 SDA / SPI0 SCK', color: '#4caf50' },
  { pin: 5,  name: 'GP3',     type: 'gpio',   alt: 'I2C1 SCL / SPI0 TX', color: '#4caf50' },
  { pin: 6,  name: 'GP4',     type: 'gpio',   alt: 'UART1 TX / I2C0 SDA / SPI0 RX', color: '#4caf50' },
  { pin: 7,  name: 'GP5',     type: 'gpio',   alt: 'UART1 RX / I2C0 SCL / SPI0 CS', color: '#4caf50' },
  { pin: 8,  name: 'GND',     type: 'ground', color: '#333333' },
  { pin: 9,  name: 'GP6',     type: 'gpio',   alt: 'I2C1 SDA / SPI0 SCK', color: '#4caf50' },
  { pin: 10, name: 'GP7',     type: 'gpio',   alt: 'I2C1 SCL / SPI0 TX', color: '#4caf50' },
  { pin: 11, name: 'GP8',     type: 'gpio',   alt: 'UART1 TX / I2C0 SDA / SPI1 RX', color: '#4caf50' },
  { pin: 12, name: 'GP9',     type: 'gpio',   alt: 'UART1 RX / I2C0 SCL / SPI1 CS', color: '#4caf50' },
  { pin: 13, name: 'GND',     type: 'ground', color: '#333333' },
  { pin: 14, name: 'GP10',    type: 'gpio',   alt: 'I2C1 SDA / SPI1 SCK', color: '#4caf50' },
  { pin: 15, name: 'GP11',    type: 'gpio',   alt: 'I2C1 SCL / SPI1 TX', color: '#4caf50' },
  { pin: 16, name: 'GP12',    type: 'gpio',   alt: 'UART0 TX / I2C0 SDA / SPI1 RX', color: '#4caf50' },
  { pin: 17, name: 'GP13',    type: 'gpio',   alt: 'UART0 RX / I2C0 SCL / SPI1 CS', color: '#4caf50' },
  { pin: 18, name: 'GND',     type: 'ground', color: '#333333' },
  { pin: 19, name: 'GP14',    type: 'gpio',   alt: 'I2C1 SDA / SPI1 SCK', color: '#4caf50' },
  { pin: 20, name: 'GP15',    type: 'gpio',   alt: 'I2C1 SCL / SPI1 TX', color: '#4caf50' },
  { pin: 21, name: 'GP16',    type: 'gpio',   alt: 'UART0 TX / I2C0 SDA / SPI0 RX', color: '#4caf50' },
  { pin: 22, name: 'GP17',    type: 'gpio',   alt: 'UART0 RX / I2C0 SCL / SPI0 CS', color: '#4caf50' },
  { pin: 23, name: 'GND',     type: 'ground', color: '#333333' },
  { pin: 24, name: 'GP18',    type: 'gpio',   alt: 'I2C1 SDA / SPI0 SCK', color: '#4caf50' },
  { pin: 25, name: 'GP19',    type: 'gpio',   alt: 'I2C1 SCL / SPI0 TX', color: '#4caf50' },
  { pin: 26, name: 'GP20',    type: 'gpio',   alt: 'UART1 TX / I2C0 SDA / SPI0 RX', color: '#4caf50' },
  { pin: 27, name: 'GP21',    type: 'gpio',   alt: 'UART1 RX / I2C0 SCL / SPI0 CS', color: '#4caf50' },
  { pin: 28, name: 'GND',     type: 'ground', color: '#333333' },
  { pin: 29, name: 'GP22',    type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 30, name: 'RUN',     type: 'special', alt: 'Reset', color: '#607d8b' },
  { pin: 31, name: 'GP26',    type: 'gpio',   alt: 'ADC0 / I2C1 SDA', color: '#e91e63' },
  { pin: 32, name: 'GP27',    type: 'gpio',   alt: 'ADC1 / I2C1 SCL', color: '#e91e63' },
  { pin: 33, name: 'GND/AGND', type: 'ground', color: '#333333' },
  { pin: 34, name: 'GP28',    type: 'gpio',   alt: 'ADC2', color: '#e91e63' },
  { pin: 35, name: 'ADC_VREF', type: 'power', alt: 'ADC Reference', color: '#ff6b35' },
  { pin: 36, name: '3V3(OUT)', type: 'power', color: '#ff6b35' },
  { pin: 37, name: '3V3_EN',  type: 'power',  alt: '3.3V Enable', color: '#ff6b35' },
  { pin: 38, name: 'GND',     type: 'ground', color: '#333333' },
  { pin: 39, name: 'VSYS',    type: 'power',  alt: 'System Voltage (1.8-5.5V)', color: '#ff0000' },
  { pin: 40, name: 'VBUS',    type: 'power',  alt: 'USB Voltage (5V)', color: '#ff0000' },
];

// BeagleBone P9 header
const BB_P9_HEADER = [
  { pin: 1,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 2,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 3,  name: 'VDD_3V3',   type: 'power',  color: '#ff6b35' },
  { pin: 4,  name: 'VDD_3V3',   type: 'power',  color: '#ff6b35' },
  { pin: 5,  name: 'VDD_5V',    type: 'power',  color: '#ff0000' },
  { pin: 6,  name: 'VDD_5V',    type: 'power',  color: '#ff0000' },
  { pin: 7,  name: 'SYS_5V',    type: 'power',  color: '#ff0000' },
  { pin: 8,  name: 'SYS_5V',    type: 'power',  color: '#ff0000' },
  { pin: 9,  name: 'PWR_BUT',   type: 'special', color: '#607d8b' },
  { pin: 10, name: 'SYS_RESET', type: 'special', color: '#607d8b' },
  { pin: 11, name: 'GPIO0_30',  type: 'gpio',   alt: 'UART4_RXD', color: '#4caf50' },
  { pin: 12, name: 'GPIO1_28',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 13, name: 'GPIO0_31',  type: 'gpio',   alt: 'UART4_TXD', color: '#4caf50' },
  { pin: 14, name: 'GPIO1_18',  type: 'gpio',   alt: 'EHRPWM1A', color: '#4caf50' },
  { pin: 15, name: 'GPIO1_16',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 16, name: 'GPIO1_19',  type: 'gpio',   alt: 'EHRPWM1B', color: '#4caf50' },
  { pin: 17, name: 'GPIO0_5',   type: 'gpio',   alt: 'I2C1_SCL', color: '#4a90d9' },
  { pin: 18, name: 'GPIO0_4',   type: 'gpio',   alt: 'I2C1_SDA', color: '#4a90d9' },
  { pin: 19, name: 'GPIO0_13',  type: 'gpio',   alt: 'I2C2_SCL', color: '#4a90d9' },
  { pin: 20, name: 'GPIO0_12',  type: 'gpio',   alt: 'I2C2_SDA', color: '#4a90d9' },
  { pin: 21, name: 'GPIO0_3',   type: 'gpio',   alt: 'UART2_TXD', color: '#9c27b0' },
  { pin: 22, name: 'GPIO0_2',   type: 'gpio',   alt: 'UART2_RXD', color: '#9c27b0' },
  { pin: 23, name: 'GPIO1_17',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 24, name: 'GPIO0_15',  type: 'gpio',   alt: 'UART1_TXD', color: '#9c27b0' },
  { pin: 25, name: 'GPIO3_21',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 26, name: 'GPIO0_14',  type: 'gpio',   alt: 'UART1_RXD', color: '#9c27b0' },
  { pin: 27, name: 'GPIO3_19',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 28, name: 'GPIO3_17',  type: 'gpio',   alt: 'SPI1_CS0', color: '#ff9800' },
  { pin: 29, name: 'GPIO3_15',  type: 'gpio',   alt: 'SPI1_D0', color: '#ff9800' },
  { pin: 30, name: 'GPIO3_16',  type: 'gpio',   alt: 'SPI1_D1', color: '#ff9800' },
  { pin: 31, name: 'GPIO3_14',  type: 'gpio',   alt: 'SPI1_SCLK', color: '#ff9800' },
  { pin: 32, name: 'VDD_ADC',   type: 'power',  alt: '1.8V ADC', color: '#ff6b35' },
  { pin: 33, name: 'AIN4',      type: 'analog', alt: 'ADC Ch4', color: '#e91e63' },
  { pin: 34, name: 'GND_ADC',   type: 'ground', color: '#333333' },
  { pin: 35, name: 'AIN6',      type: 'analog', alt: 'ADC Ch6', color: '#e91e63' },
  { pin: 36, name: 'AIN5',      type: 'analog', alt: 'ADC Ch5', color: '#e91e63' },
  { pin: 37, name: 'AIN2',      type: 'analog', alt: 'ADC Ch2', color: '#e91e63' },
  { pin: 38, name: 'AIN3',      type: 'analog', alt: 'ADC Ch3', color: '#e91e63' },
  { pin: 39, name: 'AIN0',      type: 'analog', alt: 'ADC Ch0', color: '#e91e63' },
  { pin: 40, name: 'AIN1',      type: 'analog', alt: 'ADC Ch1', color: '#e91e63' },
  { pin: 41, name: 'GPIO0_20',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 42, name: 'GPIO0_7',   type: 'gpio',   alt: 'eCAP0', color: '#4caf50' },
  { pin: 43, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 44, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 45, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 46, name: 'GND',       type: 'ground', color: '#333333' },
];

// Jetson 40-pin header — compatible physical layout with RPi 40-pin header.
// PIN values in HAL blocks must be gpiochip0 line offsets for your board.
// Run `gpioinfo /dev/gpiochip0` on the target to discover line numbers.
const JETSON_40PIN_HEADER = [
  { pin: 1,  name: '3V3',       type: 'power',  color: '#ff6b35' },
  { pin: 2,  name: '5V',        type: 'power',  color: '#ff0000' },
  { pin: 3,  name: 'I2C_SDA',   type: 'gpio',   alt: 'I2C Bus 1 SDA', color: '#4a90d9' },
  { pin: 4,  name: '5V',        type: 'power',  color: '#ff0000' },
  { pin: 5,  name: 'I2C_SCL',   type: 'gpio',   alt: 'I2C Bus 1 SCL', color: '#4a90d9' },
  { pin: 6,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 7,  name: 'GPIO_09',   type: 'gpio',   alt: 'AUD_MCLK', color: '#4caf50' },
  { pin: 8,  name: 'UART_TX',   type: 'gpio',   alt: 'THS UART TX', color: '#9c27b0' },
  { pin: 9,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 10, name: 'UART_RX',   type: 'gpio',   alt: 'THS UART RX', color: '#9c27b0' },
  { pin: 11, name: 'UART_RTS',  type: 'gpio',   alt: 'UART RTS / GPIO', color: '#4caf50' },
  { pin: 12, name: 'I2S_CLK',   type: 'gpio',   alt: 'I2S / GPIO', color: '#4caf50' },
  { pin: 13, name: 'GPIO_11',   type: 'gpio',   alt: 'SPI SCK / GPIO', color: '#4caf50' },
  { pin: 14, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 15, name: 'GPIO_19',   type: 'gpio',   alt: 'LCD_TE / GPIO', color: '#4caf50' },
  { pin: 16, name: 'GPIO_08',   type: 'gpio',   alt: 'SPI CS1 / GPIO', color: '#4caf50' },
  { pin: 17, name: '3V3',       type: 'power',  color: '#ff6b35' },
  { pin: 18, name: 'GPIO_20',   type: 'gpio',   alt: 'LCD_RST / GPIO', color: '#4caf50' },
  { pin: 19, name: 'SPI_MOSI',  type: 'gpio',   alt: 'SPI0 MOSI', color: '#ff9800' },
  { pin: 20, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 21, name: 'SPI_MISO',  type: 'gpio',   alt: 'SPI0 MISO', color: '#ff9800' },
  { pin: 22, name: 'GPIO_25',   type: 'gpio',   alt: 'SPI CS0 / GPIO', color: '#4caf50' },
  { pin: 23, name: 'SPI_SCK',   type: 'gpio',   alt: 'SPI0 SCLK', color: '#ff9800' },
  { pin: 24, name: 'SPI_CS0',   type: 'gpio',   alt: 'SPI0 CS0', color: '#ff9800' },
  { pin: 25, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 26, name: 'SPI_CS1',   type: 'gpio',   alt: 'SPI0 CS1', color: '#ff9800' },
  { pin: 27, name: 'I2C0_SDA',  type: 'gpio',   alt: 'I2C Bus 0 SDA', color: '#607d8b' },
  { pin: 28, name: 'I2C0_SCL',  type: 'gpio',   alt: 'I2C Bus 0 SCL', color: '#607d8b' },
  { pin: 29, name: 'GPIO_01',   type: 'gpio',   alt: 'CAM_AF_EN / GPIO', color: '#4caf50' },
  { pin: 30, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 31, name: 'GPIO_00',   type: 'gpio',   alt: 'UART CTS / GPIO', color: '#4caf50' },
  { pin: 32, name: 'GPIO_12',   type: 'gpio',   alt: 'LCD_BL_PWM / PWM', color: '#4caf50' },
  { pin: 33, name: 'GPIO_13',   type: 'gpio',   alt: 'SPI2 MOSI / GPIO', color: '#4caf50' },
  { pin: 34, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 35, name: 'I2S_FS',    type: 'gpio',   alt: 'I2S / GPIO', color: '#4caf50' },
  { pin: 36, name: 'UART_CTS',  type: 'gpio',   alt: 'UART CTS / GPIO', color: '#4caf50' },
  { pin: 37, name: 'GPIO_26',   type: 'gpio',   alt: 'SPI2 MISO / GPIO', color: '#4caf50' },
  { pin: 38, name: 'I2S_DIN',   type: 'gpio',   alt: 'I2S / GPIO', color: '#4caf50' },
  { pin: 39, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 40, name: 'I2S_DOUT',  type: 'gpio',   alt: 'I2S / GPIO', color: '#4caf50' },
];

// Edatec IPC pinout helper — describes industrial I/O connectors (not a GPIO header)
const edatecPinout = ({ rs485 = 0, rs232 = 0, di = 0, do_ = 0, can = 0 }) => ({
  serialPorts: [
    ...Array.from({ length: rs485 }, (_, i) => ({ index: i, type: 'RS485', label: `RS485-${i + 1}` })),
    ...Array.from({ length: rs232 }, (_, i) => ({ index: rs485 + i, type: 'RS232', label: `RS232-${i + 1}` })),
  ],
  diCount: di,
  doCount: do_,
  canCount: can,
});

// BeagleBone P8 header
const BB_P8_HEADER = [
  { pin: 1,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 2,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 3,  name: 'GPIO1_6',   type: 'gpio',   alt: 'MMC1_DAT6', color: '#4caf50' },
  { pin: 4,  name: 'GPIO1_7',   type: 'gpio',   alt: 'MMC1_DAT7', color: '#4caf50' },
  { pin: 5,  name: 'GPIO1_2',   type: 'gpio',   alt: 'MMC1_DAT2', color: '#4caf50' },
  { pin: 6,  name: 'GPIO1_3',   type: 'gpio',   alt: 'MMC1_DAT3', color: '#4caf50' },
  { pin: 7,  name: 'GPIO2_2',   type: 'gpio',   alt: 'TIMER4', color: '#4caf50' },
  { pin: 8,  name: 'GPIO2_3',   type: 'gpio',   alt: 'TIMER7', color: '#4caf50' },
  { pin: 9,  name: 'GPIO2_5',   type: 'gpio',   alt: 'TIMER5', color: '#4caf50' },
  { pin: 10, name: 'GPIO2_4',   type: 'gpio',   alt: 'TIMER6', color: '#4caf50' },
  { pin: 11, name: 'GPIO1_13',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 12, name: 'GPIO1_12',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 13, name: 'GPIO0_23',  type: 'gpio',   alt: 'EHRPWM2B', color: '#4caf50' },
  { pin: 14, name: 'GPIO0_26',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 15, name: 'GPIO1_15',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 16, name: 'GPIO1_14',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 17, name: 'GPIO0_27',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 18, name: 'GPIO2_1',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 19, name: 'GPIO0_22',  type: 'gpio',   alt: 'EHRPWM2A', color: '#4caf50' },
  { pin: 20, name: 'GPIO1_31',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 21, name: 'GPIO1_30',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 22, name: 'GPIO1_5',   type: 'gpio',   alt: 'MMC1_DAT5', color: '#4caf50' },
  { pin: 23, name: 'GPIO1_4',   type: 'gpio',   alt: 'MMC1_DAT4', color: '#4caf50' },
  { pin: 24, name: 'GPIO1_1',   type: 'gpio',   alt: 'MMC1_DAT1', color: '#4caf50' },
  { pin: 25, name: 'GPIO1_0',   type: 'gpio',   alt: 'MMC1_DAT0', color: '#4caf50' },
  { pin: 26, name: 'GPIO1_29',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 27, name: 'GPIO2_22',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 28, name: 'GPIO2_24',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 29, name: 'GPIO2_23',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 30, name: 'GPIO2_25',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 31, name: 'GPIO0_10',  type: 'gpio',   alt: 'UART5_CTS', color: '#4caf50' },
  { pin: 32, name: 'GPIO0_11',  type: 'gpio',   alt: 'UART5_RTS', color: '#4caf50' },
  { pin: 33, name: 'GPIO0_9',   type: 'gpio',   alt: 'UART4_RTS', color: '#4caf50' },
  { pin: 34, name: 'GPIO2_17',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 35, name: 'GPIO0_8',   type: 'gpio',   alt: 'UART4_CTS', color: '#4caf50' },
  { pin: 36, name: 'GPIO2_16',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 37, name: 'GPIO2_14',  type: 'gpio',   alt: 'UART5_TXD', color: '#4caf50' },
  { pin: 38, name: 'GPIO2_15',  type: 'gpio',   alt: 'UART5_RXD', color: '#4caf50' },
  { pin: 39, name: 'GPIO2_12',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 40, name: 'GPIO2_13',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 41, name: 'GPIO2_10',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 42, name: 'GPIO2_11',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 43, name: 'GPIO2_8',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 44, name: 'GPIO2_9',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 45, name: 'GPIO2_6',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 46, name: 'GPIO2_7',   type: 'gpio',   alt: '', color: '#4caf50' },
];

export const BOARD_FAMILIES = [
  {
    name: 'Raspberry Pi',
    icon: '🍓',
    boards: [
      {
        id: 'rpi_5',
        name: 'Raspberry Pi 5',
        cpu: 'Broadcom BCM2712 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB / 8GB LPDDR4X',
        storage: 'microSD / NVMe (M.2 HAT)',
        connectivity: 'WiFi 5, BT 5.0, Gigabit Ethernet',
        gpio: 40,
        usb: '2x USB 3.0, 2x USB 2.0',
        display: '2x micro HDMI (4Kp60)',
        pinout: RPI_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM'],
      },
      {
        id: 'rpi_4b',
        name: 'Raspberry Pi 4 Model B',
        cpu: 'Broadcom BCM2711 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '2GB / 4GB / 8GB LPDDR4',
        storage: 'microSD',
        connectivity: 'WiFi 5, BT 5.0, Gigabit Ethernet',
        gpio: 40,
        usb: '2x USB 3.0, 2x USB 2.0',
        display: '2x micro HDMI (4Kp60)',
        pinout: RPI_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM'],
      },
      {
        id: 'rpi_3b_plus',
        name: 'Raspberry Pi 3 Model B+',
        cpu: 'Broadcom BCM2837B0 (Quad Cortex-A53 @ 1.4GHz)',
        arch: 'aarch64',
        ram: '1GB LPDDR2',
        storage: 'microSD',
        connectivity: 'WiFi 4, BT 4.2, Gigabit Ethernet (300Mbps)',
        gpio: 40,
        usb: '4x USB 2.0',
        display: 'HDMI (1080p)',
        pinout: RPI_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM'],
      },
      {
        id: 'rpi_3b',
        name: 'Raspberry Pi 3 Model B',
        cpu: 'Broadcom BCM2837 (Quad Cortex-A53 @ 1.2GHz)',
        arch: 'aarch64',
        ram: '1GB LPDDR2',
        storage: 'microSD',
        connectivity: 'WiFi 4, BT 4.1, 100Mbps Ethernet',
        gpio: 40,
        usb: '4x USB 2.0',
        display: 'HDMI (1080p)',
        pinout: RPI_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM'],
      },
      {
        id: 'rpi_zero_2w',
        name: 'Raspberry Pi Zero 2 W',
        cpu: 'Broadcom BCM2710A1 (Quad Cortex-A53 @ 1GHz)',
        arch: 'aarch64',
        ram: '512MB LPDDR2',
        storage: 'microSD',
        connectivity: 'WiFi 4, BT 4.2',
        gpio: 40,
        usb: '1x micro USB (OTG)',
        display: 'mini HDMI',
        pinout: RPI_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM'],
      },
      {
        id: 'rpi_pico',
        name: 'Raspberry Pi Pico',
        cpu: 'RP2040 (Dual Cortex-M0+ @ 133MHz)',
        arch: 'arm-cortex-m0+',
        ram: '264KB SRAM',
        storage: '2MB Flash',
        connectivity: 'None (Pico W has WiFi)',
        gpio: 26,
        usb: '1x micro USB',
        display: 'N/A',
        pinout: RPI_PICO_PINS,
        pinLayout: 'pico',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC'],
      },
      {
        id: 'rpi_pico_w',
        name: 'Raspberry Pi Pico W',
        cpu: 'RP2040 (Dual Cortex-M0+ @ 133MHz)',
        arch: 'arm-cortex-m0+',
        ram: '264KB SRAM',
        storage: '2MB Flash',
        connectivity: 'WiFi 4, BT 5.2 (CYW43439)',
        gpio: 26,
        usb: '1x micro USB',
        display: 'N/A',
        pinout: RPI_PICO_PINS,
        pinLayout: 'pico',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC'],
      },
    ]
  },
  {
    name: 'BeagleBone',
    icon: '🦴',
    boards: [
      {
        id: 'bb_black',
        name: 'BeagleBone Black',
        cpu: 'TI AM3358 (Cortex-A8 @ 1GHz)',
        arch: 'armv7',
        ram: '512MB DDR3',
        storage: '4GB eMMC + microSD',
        connectivity: '10/100 Ethernet',
        gpio: 65,
        usb: '1x USB 2.0 Host, 1x mini USB Client',
        display: 'micro HDMI',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU'],
      },
      {
        id: 'bb_black_wireless',
        name: 'BeagleBone Black Wireless',
        cpu: 'TI AM3358 (Cortex-A8 @ 1GHz)',
        arch: 'armv7',
        ram: '512MB DDR3',
        storage: '4GB eMMC + microSD',
        connectivity: 'WiFi, BT 4.1',
        gpio: 65,
        usb: '1x USB 2.0 Host, 1x mini USB Client',
        display: 'micro HDMI',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU'],
      },
      {
        id: 'bb_green',
        name: 'BeagleBone Green',
        cpu: 'TI AM3358 (Cortex-A8 @ 1GHz)',
        arch: 'armv7',
        ram: '512MB DDR3',
        storage: '4GB eMMC + microSD',
        connectivity: '10/100 Ethernet',
        gpio: 65,
        usb: '1x USB 2.0 Host, 1x mini USB Client',
        display: 'N/A (No HDMI)',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU', 'Grove'],
      },
      {
        id: 'bb_green_wireless',
        name: 'BeagleBone Green Wireless',
        cpu: 'TI AM3358 (Cortex-A8 @ 1GHz)',
        arch: 'armv7',
        ram: '512MB DDR3',
        storage: '4GB eMMC + microSD',
        connectivity: 'WiFi, BT 4.1',
        gpio: 65,
        usb: '1x USB 2.0 Host, 1x micro USB Client',
        display: 'N/A (No HDMI)',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU', 'Grove'],
      },
      {
        id: 'bb_ai',
        name: 'BeagleBone AI',
        cpu: 'TI AM5729 (Dual Cortex-A15 @ 1.5GHz)',
        arch: 'armv7',
        ram: '1GB DDR3L',
        storage: '16GB eMMC + microSD',
        connectivity: 'WiFi 5, BT 4.2, Gigabit Ethernet',
        gpio: 65,
        usb: '1x USB 3.0 Type-A, 1x USB Type-C',
        display: 'micro HDMI',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU'],
      },
      {
        id: 'bb_ai64',
        name: 'BeagleBone AI-64',
        cpu: 'TI TDA4VM (Dual Cortex-A72 @ 2GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '16GB eMMC + microSD',
        connectivity: 'WiFi 6, BT 5.1, Gigabit Ethernet',
        gpio: 65,
        usb: '2x USB 3.0 Type-A, 1x USB Type-C',
        display: 'mini DP, micro HDMI',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU', 'CSI'],
      },
    ]
  },
  {
    name: 'Edatec IPC',
    icon: '🏭',
    boards: [
      // ── ED-IPC2000 series: CM4 Basic ──────────────────────────────────────
      {
        id: 'edatec_ipc2010',
        name: 'ED-IPC2010',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({}),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      {
        id: 'edatec_ipc2020',
        name: 'ED-IPC2020',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({}),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PCM'],
      },
      // ── ED-IPC2100 series: CM4 + 4x isolated RS232/RS485 ─────────────────
      {
        id: 'edatec_ipc2110',
        name: 'ED-IPC2110',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 2, rs232: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      {
        id: 'edatec_ipc2120',
        name: 'ED-IPC2120',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 2, rs232: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PCM'],
      },
      {
        id: 'edatec_ipc2130',
        name: 'ED-IPC2130',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 3, rs232: 1 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      {
        id: 'edatec_ipc2140',
        name: 'ED-IPC2140',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 4 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      // ── ED-IPC2200 series: CM4 + 3x GigE + mSATA ─────────────────────────
      {
        id: 'edatec_ipc2200',
        name: 'ED-IPC2200',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + mSATA SSD',
        connectivity: '3x Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({}),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      // ── ED-IPC2400 series: CM4 + 1x RS232 DB9 + combo serial ─────────────
      {
        id: 'edatec_ipc2410',
        name: 'ED-IPC2410',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 2, rs232: 1 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      {
        id: 'edatec_ipc2420',
        name: 'ED-IPC2420',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 1, rs232: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      {
        id: 'edatec_ipc2430',
        name: 'ED-IPC2430',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs232: 3 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      // ── ED-IPC2610 series: CM4 + 8DI + 8DO + 4x serial ───────────────────
      {
        id: 'edatec_ipc2612',
        name: 'ED-IPC2612',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 16,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 2, rs232: 2, di: 8, do_: 8 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO'],
      },
      {
        id: 'edatec_ipc2613',
        name: 'ED-IPC2613',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 16,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 3, rs232: 1, di: 8, do_: 8 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO'],
      },
      {
        id: 'edatec_ipc2614',
        name: 'ED-IPC2614',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 16,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 4, di: 8, do_: 8 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO'],
      },
      // ── ED-IPC2620 series: CM4 + 4DI + 4DO + 1CAN + 4x serial ────────────
      {
        id: 'edatec_ipc2622',
        name: 'ED-IPC2622',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 8,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 2, rs232: 2, di: 4, do_: 4, can: 1 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO', 'CAN'],
      },
      {
        id: 'edatec_ipc2623',
        name: 'ED-IPC2623',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 8,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 3, rs232: 1, di: 4, do_: 4, can: 1 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO', 'CAN'],
      },
      {
        id: 'edatec_ipc2624',
        name: 'ED-IPC2624',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 8,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 4, di: 4, do_: 4, can: 1 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO', 'CAN'],
      },
      // ── ED-IPC2630 series: CM4 + 8DI + 8DO + 2CAN + 4x serial ───────────
      {
        id: 'edatec_ipc2632',
        name: 'ED-IPC2632',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 16,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 2, rs232: 2, di: 8, do_: 8, can: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO', 'CAN'],
      },
      {
        id: 'edatec_ipc2633',
        name: 'ED-IPC2633',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 16,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 3, rs232: 1, di: 8, do_: 8, can: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO', 'CAN'],
      },
      {
        id: 'edatec_ipc2634',
        name: 'ED-IPC2634',
        cpu: 'Broadcom BCM2711 CM4 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 16,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 4, di: 8, do_: 8, can: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO', 'CAN'],
      },
      // ── ED-IPC3020: Pi5-based, 2-port serial ─────────────────────────────
      {
        id: 'edatec_ipc3020',
        name: 'ED-IPC3020',
        cpu: 'Broadcom BCM2712 Pi5 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4X',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 1, rs232: 1 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      // ── ED-IPC3100 series: CM5 + 4x isolated RS232/RS485 ─────────────────
      {
        id: 'edatec_ipc3110',
        name: 'ED-IPC3110',
        cpu: 'Broadcom BCM2712 CM5 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4X',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 2, rs232: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      {
        id: 'edatec_ipc3120',
        name: 'ED-IPC3120',
        cpu: 'Broadcom BCM2711 CM5 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4X',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 2, rs232: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PCM'],
      },
      {
        id: 'edatec_ipc3130',
        name: 'ED-IPC3130',
        cpu: 'Broadcom BCM2712 CM5 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4X',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 3, rs232: 1 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      {
        id: 'edatec_ipc3140',
        name: 'ED-IPC3140',
        cpu: 'Broadcom BCM2712 CM5 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4X',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 0,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 4 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART'],
      },
      // ── ED-IPC3630 series: CM5 + 8DI + 8DO + 2CAN + 4x serial ───────────
      {
        id: 'edatec_ipc3632',
        name: 'ED-IPC3632',
        cpu: 'Broadcom BCM2712 CM5 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4X',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 16,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 2, rs232: 2, di: 8, do_: 8, can: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO', 'CAN'],
      },
      {
        id: 'edatec_ipc3633',
        name: 'ED-IPC3633',
        cpu: 'Broadcom BCM2712 CM5 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4X',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 16,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 3, rs232: 1, di: 8, do_: 8, can: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO', 'CAN'],
      },
      {
        id: 'edatec_ipc3634',
        name: 'ED-IPC3634',
        cpu: 'Broadcom BCM2712 CM5 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4X',
        storage: '8GB eMMC + M.2 SSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 16,
        usb: '2x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0',
        pinout: edatecPinout({ rs485: 4, di: 8, do_: 8, can: 2 }),
        pinLayout: 'edatec_ipc',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'DI', 'DO', 'CAN'],
      },
    ]
  },
  {
    name: 'NVIDIA Jetson',
    icon: '🤖',
    boards: [
      {
        id: 'jetson_nano',
        name: 'Jetson Nano Developer Kit',
        cpu: 'NVIDIA Tegra X1 (Quad Cortex-A57 @ 1.48GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: 'microSD / eMMC (production module)',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '4x USB 3.0, 1x micro USB (power/device)',
        display: 'HDMI 2.0, DP 1.2',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN'],
      },
      {
        id: 'jetson_tx2',
        name: 'Jetson TX2 Developer Kit',
        cpu: 'NVIDIA Parker (Dual Denver 2 + Quad Cortex-A57 @ 2GHz)',
        arch: 'aarch64',
        ram: '8GB LPDDR4',
        storage: '32GB eMMC',
        connectivity: 'Gigabit Ethernet, WiFi 802.11ac, BT 4.1',
        gpio: 40,
        usb: '3x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0, DP 1.2, eDP 1.4',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN'],
      },
      {
        id: 'jetson_xavier_nx',
        name: 'Jetson Xavier NX Developer Kit',
        cpu: 'NVIDIA Volta (6-core Carmel ARMv8.2 @ 1.9GHz)',
        arch: 'aarch64',
        ram: '8GB / 16GB LPDDR4x',
        storage: 'microSD / 16GB eMMC',
        connectivity: 'Gigabit Ethernet, WiFi 802.11ac, BT 5.0',
        gpio: 40,
        usb: '4x USB 3.1 Gen 2, 1x USB 2.0 Micro-B',
        display: 'HDMI 2.0, DP 1.4',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN'],
      },
      {
        id: 'jetson_agx_xavier',
        name: 'Jetson AGX Xavier Developer Kit',
        cpu: 'NVIDIA Xavier (8-core Carmel ARMv8.2 @ 2.265GHz)',
        arch: 'aarch64',
        ram: '16GB / 32GB LPDDR4x',
        storage: '32GB eMMC',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '2x USB 3.1 Gen 2 Type-A, 1x USB 3.1 Gen 2 Type-C',
        display: 'HDMI 2.0, DP 1.4, eDP 1.4',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN'],
      },
      {
        id: 'jetson_orin_nano',
        name: 'Jetson Orin Nano Developer Kit',
        cpu: 'NVIDIA Orin (6-core Cortex-A78AE @ 1.5GHz)',
        arch: 'aarch64',
        ram: '4GB / 8GB LPDDR5',
        storage: 'microSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '4x USB 3.2 Gen 2, 1x USB 2.0 Micro-B',
        display: 'HDMI 2.1, DP 1.4',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN'],
      },
      {
        id: 'jetson_orin_nx',
        name: 'Jetson Orin NX Developer Kit',
        cpu: 'NVIDIA Orin (8/10-core Cortex-A78AE @ 2GHz)',
        arch: 'aarch64',
        ram: '8GB / 16GB LPDDR5',
        storage: 'microSD / NVMe',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '4x USB 3.2 Gen 2, 1x USB 2.0 Micro-B',
        display: 'HDMI 2.1, DP 1.4',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN'],
      },
      {
        id: 'jetson_agx_orin',
        name: 'Jetson AGX Orin Developer Kit',
        cpu: 'NVIDIA Orin (12-core Cortex-A78AE @ 2.2GHz)',
        arch: 'aarch64',
        ram: '32GB / 64GB LPDDR5',
        storage: '64GB eMMC / NVMe',
        connectivity: 'Gigabit Ethernet (2x)',
        gpio: 40,
        usb: '4x USB 3.2 Gen 2 Type-A, 1x USB 3.2 Gen 2 Type-C',
        display: 'HDMI 2.1, DP 1.4, eDP 1.4',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN'],
      },
    ]
  }
];

// Flat lookup helper
export function getBoardById(boardId) {
  for (const family of BOARD_FAMILIES) {
    const board = family.boards.find(b => b.id === boardId);
    if (board) return { ...board, family: family.name };
  }
  return null;
}

// Get family of a board
export function getBoardFamily(boardId) {
  for (const family of BOARD_FAMILIES) {
    if (family.boards.some(b => b.id === boardId)) return family.name;
  }
  return null;
}
