export const COMPONENT_CATEGORIES = [
    {
        key: 'indicators',
        label: 'Indicators',
        components: ['LED', 'ALARM', 'NUMERIC_DISPLAY', 'PROGRESS', 'GAUGE', 'CHART'],
    },
    {
        key: 'controls',
        label: 'Controls',
        components: ['BUTTON', 'TOGGLE_BUTTON', 'SWITCH', 'SLIDER', 'NUMERIC_INPUT'],
    },
    {
        key: 'display',
        label: 'Display',
        components: ['LABEL', 'RECTANGLE', 'CIRCLE', 'LINE'],
    },
];

export const COMPONENT_DEFS = {
    LED: {
        label: 'LED',
        icon: '⬤',
        defaultSize: { w: 64, h: 64 },
        defaultProps: {
            variable: '',
            onColor: '#00e676',
            offColor: '#1a1a1a',
            borderColor: '#555',
            label: '',
            labelPosition: 'bottom',
            fontSize: 11,
        },
    },
    ALARM: {
        label: 'Alarm',
        icon: '⚠',
        defaultSize: { w: 80, h: 80 },
        defaultProps: {
            variable: '',
            activeColor: '#f14c4c',
            inactiveColor: '#2a2a2a',
            label: 'ALARM',
            blink: true,
            fontSize: 12,
        },
    },
    NUMERIC_DISPLAY: {
        label: 'Numeric',
        icon: '#',
        defaultSize: { w: 150, h: 52 },
        defaultProps: {
            variable: '',
            decimals: 2,
            unit: '',
            color: '#4ec9b0',
            background: '#0a0f14',
            borderColor: '#1e2a38',
            fontSize: 24,
        },
    },
    PROGRESS: {
        label: 'Progress',
        icon: '▬',
        defaultSize: { w: 200, h: 30 },
        defaultProps: {
            variable: '',
            min: 0,
            max: 100,
            color: '#007acc',
            background: '#1a1a1a',
            borderColor: '#2a2a2a',
            showValue: true,
            label: '',
        },
    },
    GAUGE: {
        label: 'Gauge',
        icon: '◔',
        defaultSize: { w: 150, h: 140 },
        defaultProps: {
            variable: '',
            min: 0,
            max: 100,
            unit: '',
            label: '',
            arcColor: '#007acc',
            bgArcColor: '#1e2a38',
            needleColor: '#e0e0e0',
            valueColor: '#e0e0e0',
        },
    },
    CHART: {
        label: 'Trend',
        icon: '↗',
        defaultSize: { w: 320, h: 180 },
        defaultProps: {
            variable: '',
            maxPoints: 100,
            lineColor: '#007acc',
            fillColor: 'rgba(0,122,204,0.15)',
            background: '#0a0f14',
            gridColor: '#1a2030',
            label: '',
            unit: '',
            autoScale: true,
        },
    },
    BUTTON: {
        label: 'Button',
        icon: '⬛',
        defaultSize: { w: 120, h: 46 },
        defaultProps: {
            variable: '',
            label: 'Button',
            mode: 'momentary',
            onColor: '#007acc',
            offColor: '#252525',
            textColor: '#ffffff',
            borderColor: '#3a3a3a',
            borderRadius: 3,
            fontSize: 13,
        },
    },
    TOGGLE_BUTTON: {
        label: 'Toggle',
        icon: '⊡',
        defaultSize: { w: 120, h: 46 },
        defaultProps: {
            variable: '',
            labelOn: 'ON',
            labelOff: 'OFF',
            onColor: '#007a4d',
            offColor: '#252525',
            textColor: '#ffffff',
            borderColor: '#3a3a3a',
            borderRadius: 3,
            fontSize: 13,
        },
    },
    SWITCH: {
        label: 'Switch',
        icon: '⏻',
        defaultSize: { w: 90, h: 42 },
        defaultProps: {
            variable: '',
            onColor: '#007acc',
            offColor: '#333',
            label: '',
            labelPosition: 'right',
            fontSize: 12,
        },
    },
    SLIDER: {
        label: 'Slider',
        icon: '⊟',
        defaultSize: { w: 220, h: 44 },
        defaultProps: {
            variable: '',
            min: 0,
            max: 100,
            step: 1,
            orientation: 'horizontal',
            trackColor: '#2a2a2a',
            thumbColor: '#007acc',
            showValue: true,
        },
    },
    NUMERIC_INPUT: {
        label: 'Num Input',
        icon: '⌨',
        defaultSize: { w: 150, h: 46 },
        defaultProps: {
            variable: '',
            decimals: 0,
            label: '',
            color: '#e0e0e0',
            background: '#1a1a1a',
            borderColor: '#3a3a3a',
            fontSize: 14,
        },
    },
    LABEL: {
        label: 'Label',
        icon: 'T',
        defaultSize: { w: 130, h: 32 },
        defaultProps: {
            text: 'Label',
            variable: '',
            decimals: 2,
            unit: '',
            fontSize: 13,
            fontWeight: 'normal',
            color: '#d4d4d4',
            align: 'left',
            background: 'transparent',
        },
    },
    RECTANGLE: {
        label: 'Rectangle',
        icon: '□',
        defaultSize: { w: 160, h: 100 },
        defaultProps: {
            background: 'transparent',
            borderColor: '#444',
            borderWidth: 1,
            borderRadius: 0,
            label: '',
            labelColor: '#888',
            fontSize: 11,
        },
    },
    CIRCLE: {
        label: 'Circle',
        icon: '○',
        defaultSize: { w: 100, h: 100 },
        defaultProps: {
            background: 'transparent',
            borderColor: '#444',
            borderWidth: 1,
        },
    },
    LINE: {
        label: 'Line',
        icon: '─',
        defaultSize: { w: 200, h: 2 },
        defaultProps: {
            color: '#444',
            thickness: 1,
            style: 'solid',
            orientation: 'horizontal',
        },
    },
};
